<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>52&nbsp; Fehlerrechnung – Bausteine Python</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../books/m-sensordatenanalyse/skript/übung-hooke.html" rel="next">
<link href="../../../books/m-sensordatenanalyse/skript/lineare-parameterschätzung.html" rel="prev">
<link href="../../../books/shared-media/logo/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-e22fbe6e69edb8577f7b7bd0719516f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../books/m-sensordatenanalyse/index.html">a-energiedatenanalyse</a></li><li class="breadcrumb-item"><a href="../../../books/m-sensordatenanalyse/skript/fehlerrechnung.html"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Fehlerrechnung</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../../index.html" class="sidebar-logo-link">
      <img src="../../../books/shared-media/logo/logo_with_text.svg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Bausteine Python</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FireDynamics/bcd-bausteine-python" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../../../Bausteine-Python.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Übersicht</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">w-pseudocode</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pseudocode/Pseudocode.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Werkzeugbaustein Pseudocode</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">w-python-minimal</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Werkzeugbaustein Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/skript/datentypen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Datentypen verstehen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/skript/flusskontrolle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Entscheidungen und Wiederholungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/skript/listen_iterationen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Mehrere Werte speichern</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/skript/funktionen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Wiederverwendbarer Code mit Funktionen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/skript/lesen_schreiben.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Arbeiten mit Dateien</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-minimal/skript/daswichtigste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Das Wichtigste</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">w-python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Werkzeugbaustein Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Einleitung: Datenanalyse mit Python</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/datentypen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Datentypen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/funktionen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Funktionen: Grundlagen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/flusskontrolle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Flusskontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/sammeltypen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sammeltypen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/funktionen-definieren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Eigene Funktionen definieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/dateien-lesen-und-schreiben.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Dateien lesen und schreiben</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/module-und-pakete-importieren.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Module und Pakete importieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python/skript/daswichtigste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Das Wichtigste</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">w-python-numpy</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Werkzeugbaustein NumPy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Einführung NumPy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/array_creation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Erstellen von NumPy arrays</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/array_info.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Größe, Struktur und Typ</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/array_calculation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Rechnen mit Arrays</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/array_slicing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Slicing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/array_manipulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Array Manipulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/array_read_n_write.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Lesen und Schreiben von Dateien</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/array_images.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Arbeiten mit Bildern</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/skript/assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Lernzielkontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/uebungen/uebung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Übung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-numpy/klausurfragen/klausurfragen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Klausurfragen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">w-python-matplotlib</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-matplotlib/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preamble</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-matplotlib/skript/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Einführung in Matplotlib</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-matplotlib/skript/basic_plot_types.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Diagrammtypen in Matplotlib</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-matplotlib/skript/adapting_plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Anpassung und Gestaltung von Plots in Matplotlib</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-matplotlib/skript/advanced_techniques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Erweiterte Techniken in Matplotlib</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-python-matplotlib/skript/scientific_plotting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Best Practices in Matplotlib: Fehler und Verbesserungen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">w-python-pandas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pandas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Werkzeugbaustein Pandas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pandas/skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Einleitung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pandas/skript/operationen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Operationen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pandas/skript/plotting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Grafikerstellung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pandas/skript/datentypen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Datentypen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pandas/skript/datetime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Zeitreihen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/w-pandas/skript/dateien.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Dateien lesen und schreiben</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">m-numerik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-numerik/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preamble</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-numerik/skript/intro_integrale.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Integration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-numerik/skript/intro_ableitungen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Differentiation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">m-einlesen-strukturierter-datensaetze</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-einlesen-strukturierter-datensaetze/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodenbaustein Einlesen strukturierter Datensätze</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-einlesen-strukturierter-datensaetze/skript/einlesen-strukturierter-datensaetze.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Einleitung</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">m-datenfitting-und-optimierung</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-datenfitting-und-optimierung/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodenbaustein Datenfitting und Datenoptimierung</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-datenfitting-und-optimierung/skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Einleitung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-datenfitting-und-optimierung/skript/interpolation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Interpolation – Lücken schließen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-datenfitting-und-optimierung/skript/fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Fitting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-datenfitting-und-optimierung/skript/splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Splines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-datenfitting-und-optimierung/skript/glaetten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Trendglättung – Rauschen reduzieren</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-datenfitting-und-optimierung/skript/uebungen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Übungen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">a-energiedatenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodenbaustein Sensordatenanalyse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/skript/einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Das Prinzip von Messungen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/skript/normalverteilung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Die Normalverteilung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/skript/lineare-parameterschätzung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Lineare Parameterschätzung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/skript/fehlerrechnung.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Fehlerrechnung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/skript/übung-hooke.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Übung Hooke’sches Gesetz</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/skript/kalibrierung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Kalibrierung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/m-sensordatenanalyse/skript/beispiel-eiskochen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Beispiel Eis kochen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">a-analyse-von-zeitdaten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preamble</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/01-einleitung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">1 Einordnung: Zeitreihen als Messprozess</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/02-vorverarbeitung-validierung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">2 Vorverarbeitung &amp; Validierung einer Zeitreihe</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/03-resampling-alignment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">3 Resampling &amp; Alignment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/04-glaettung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">4 Glättung &amp; Rauschreduktion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/05-trend-saison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">5 Trend &amp; Saison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/06-lags-autokorrelation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">6 Lags &amp; Autokorrelation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/07-anomalien.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">7 Anomalien</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/08-forecasting-baselines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">8 Forecasting-Baselines &amp; Bewertung</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/09-lernzielkontrolle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">9 Lernzielkontrolle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/10-uebung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">10 Übung: Zeitreihen-Workflow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-analyse-von-zeitdaten/skript/11-klausurfragen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">11 Klausurfragen</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">a-energiedatenanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-energiedatenanalyse/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preamble</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-energiedatenanalyse/skript/energiedatenanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Energiedatenanalyse</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true">
 <span class="menu-text">a-auswertung-fds-daten</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-auswertung-fds-daten/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preamble</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-auswertung-fds-daten/skript/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Einführung in ASET</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-auswertung-fds-daten/skript/aset.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Verfügbare sichere Evakuierungszeit (ASET)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-auswertung-fds-daten/skript/fdsreader.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Fdsreader</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-auswertung-fds-daten/uebungen/uebung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">uebung.html</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../books/a-auswertung-fds-daten/klausurfragen/klausurfragen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">klausurfragen.html</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#bevor-es-losgeht" id="toc-bevor-es-losgeht" class="nav-link active" data-scroll-target="#bevor-es-losgeht"><span class="header-section-number">52.1</span> Bevor es losgeht</a></li>
  <li><a href="#fehlerarten" id="toc-fehlerarten" class="nav-link" data-scroll-target="#fehlerarten"><span class="header-section-number">52.2</span> Fehlerarten</a></li>
  <li><a href="#grundbegriffe-nach-din-1319" id="toc-grundbegriffe-nach-din-1319" class="nav-link" data-scroll-target="#grundbegriffe-nach-din-1319"><span class="header-section-number">52.3</span> Grundbegriffe nach DIN 1319</a></li>
  <li><a href="#absolute-und-relative-fehler" id="toc-absolute-und-relative-fehler" class="nav-link" data-scroll-target="#absolute-und-relative-fehler"><span class="header-section-number">52.4</span> Absolute und relative Fehler</a></li>
  <li><a href="#größtfehler" id="toc-größtfehler" class="nav-link" data-scroll-target="#größtfehler"><span class="header-section-number">52.5</span> Größtfehler</a></li>
  <li><a href="#signifikante-stellen" id="toc-signifikante-stellen" class="nav-link" data-scroll-target="#signifikante-stellen"><span class="header-section-number">52.6</span> Signifikante Stellen</a></li>
  <li><a href="#methoden-der-fehlerrechnung" id="toc-methoden-der-fehlerrechnung" class="nav-link" data-scroll-target="#methoden-der-fehlerrechnung"><span class="header-section-number">52.7</span> Methoden der Fehlerrechnung</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/FireDynamics/bcd-bausteine-python/blob/main/books/m-sensordatenanalyse/skript/fehlerrechnung.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../books/m-sensordatenanalyse/index.html">a-energiedatenanalyse</a></li><li class="breadcrumb-item"><a href="../../../books/m-sensordatenanalyse/skript/fehlerrechnung.html"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Fehlerrechnung</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Fehlerrechnung</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="border quarto-layout-panel" data-layout="[[5, 90, 5], [1]]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 90.0%;justify-content: flex-start;">
<p>“Das Experimentieren ist ein dornenvoller Weg und so ganz sicher ist man sich nie.”</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<p>Wagner, Paul. 2015. “Einführung in die Physik I. PH I - 04 - Die Messgenauigkeit / Fehlerrechnung Teil 1.” Universität Wien Physik, <a href="https://youtu.be/sF2_1YNiWXI?feature=shared&amp;t=245">YouTube</a>, Zeitstempel 04:05</p>
</div>
</div>
</div>
<p>&nbsp;</p>
<p>Kein Messgerät misst exakt und nicht alle Umwelteinflüsse können kontrolliert werden. Das Ziel der Fehlerrechnung ist es, die sich daraus ergebende Abweichung der Messwerte um den wahren Wert einer Größe zu quantifizieren.</p>
<section id="bevor-es-losgeht" class="level2" data-number="52.1">
<h2 data-number="52.1" class="anchored" data-anchor-id="bevor-es-losgeht"><span class="header-section-number">52.1</span> Bevor es losgeht</h2>
<p>Das Thema ist jedoch mit einigen Schwierigkeiten verbunden, die den Einstieg und die eigenständige Vertiefung des Themas erschweren.</p>
<section id="der-begriff-des-fehlers" class="level3" data-number="52.1.1">
<h3 data-number="52.1.1" class="anchored" data-anchor-id="der-begriff-des-fehlers"><span class="header-section-number">52.1.1</span> Der Begriff des Fehlers</h3>
<p>Das Wort Fehler steckt zwar schon in der Überschrift dieses Kapitels, doch handelt es sich seit 1995 nicht mehr um einen genormten Begriff. Die DIN 1319 normt Grundbegriffe und Verfahren der Messtechnik. Die Norm ersetzt den Begriff des Fehlers durch die Begriffe <strong>Messabweichung</strong> und <strong>Messunsicherheit</strong>, umfasst aber darüber hinaus eine Vielzahl aufeinander bezogener Begriffsdefinitionen, Anmerkungen und Bemerkungen.</p>
<p>In diesem Kapitel werden die in der Fehlerrechnung gebräuchlichen Begriffe aufgegriffen, um die Verbindung zu den genormten Begriffen herzustellen. Im Allgemeinen werden jedoch die genormten Begriffe verwendet. Um den Einstieg in das Thema zu erleichtern, beschränkt sich dieses Kapitel auf Messungen mit:</p>
<ul>
<li>unkorrelierten Eingangsgrößen und</li>
<li>vernachlässigbarer Unsicherheit über die systematische Messabweichung.</li>
</ul>
</section>
<section id="konfidenzniveau" class="level3" data-number="52.1.2">
<h3 data-number="52.1.2" class="anchored" data-anchor-id="konfidenzniveau"><span class="header-section-number">52.1.2</span> Konfidenzniveau</h3>
<p>Wiederholte Messungen enthalten eine zufällige Komponente statistischer Unsicherheit. Die statistische Unsicherheit kann immer nur mit einer Vertrauenswahrscheinlichkeit angegeben werden. Die Berechnung von Konfidenzintervallen haben wir in <a href="#sec-normalverteilung" class="quarto-xref"><span class="quarto-unresolved-ref">sec-normalverteilung</span></a> und <a href="#sec-hooke" class="quarto-xref"><span class="quarto-unresolved-ref">sec-hooke</span></a> behandelt.</p>
<p>Zur statistischen Analyse gehört als erster Schritt, das Konfidenzniveau, das gelten soll, festzulegen. Hieraus leiten sich die zu verwendenden Vielfachen der Standardabweichung <span class="math inline">\(s\)</span> bzw. des Korrekturfaktors <span class="math inline">\(t\)</span> ab. Hierbei gibt es je nach Disziplin unterschiedliche Konventionen.</p>
<div class="quarto-layout-panel" data-layout="[5, 90, 5]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 90.0%;justify-content: flex-start;">
<p>“In der Physik und der Vermessungstechnik begnügt man sich mit einer statistischen Sicherheit von 68,3% und setzt deshalb t = 1 […] (In der Industrie wird t = 2, in der Biologie t = 3 bevorzugt.)” <span class="citation" data-cites="HS-Aalen-2016">[@HS-Aalen-2016 S. 4]</span></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
</div>
</div>
<p>In der ingenieurswissenschaftlichen Literatur wird dieser Schritt nicht immer explizit gemacht (weil es üblich ist, <span class="math inline">\(1 s\)</span> bzw. <span class="math inline">\(1 t\)</span> zu verwenden). Dagegen heißt es in der DIN 1319: “Es ist üblich, das Vertrauensniveau (<span class="math inline">\(1 - \alpha\)</span>) in Prozent anzugeben, wobei meist <span class="math inline">\(\alpha = 0,05\)</span> (Vertrauensniveau: 95 %) benutzt wird.” <span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 17]</span></p>
</section>
<section id="notation" class="level3" data-number="52.1.3">
<h3 data-number="52.1.3" class="anchored" data-anchor-id="notation"><span class="header-section-number">52.1.3</span> Notation</h3>
<p>Die Notation ist komplex: Neben dem lateinischen und griechischen Alphabet wird auch das kyrillische Alphabet verwendet. Trotzdem lassen sich Dopplungen von Symbolen für Formelzeichen und Einheiten nicht immer vermeiden (und die Federkonstante ist in dieser Hinsicht der denkbar ungünstigste Fall).</p>
<p>Die Notation wird außerdem uneinheitlich gehandhabt. Während in der DIN 1319 Messabweichungen mit <span class="math inline">\(e\)</span> notiert werden, sind in der Literatur <span class="math inline">\(\epsilon\)</span> (epsilon) und <span class="math inline">\(\Delta\)</span> (Delta) gebräuchlich, wobei letzteres auch für den Größtfehler verwendet wird.</p>
<p>Übrigens: Das in der DIN verwendete <span class="math inline">\(e\)</span> steht für error, also Fehler ( ¯\_(ツ)_/¯ ).</p>
</section>
</section>
<section id="fehlerarten" class="level2" data-number="52.2">
<h2 data-number="52.2" class="anchored" data-anchor-id="fehlerarten"><span class="header-section-number">52.2</span> Fehlerarten</h2>
<p>Bei Messungen können unterschiedliche Arten von Abweichungen des Messergebnisses vom tatsächlichen Wert der gemessenen Größe auftreten. Am gebräuchlichsten ist die Unterteilung in grobe, systematische und zufällige <em>Fehler</em>. Nach DIN 1319 sollte besser von systematischen und zufälligen Messabweichungen gesprochen werden. Grobe Fehler werden in der Norm jedoch nicht behandelt und hier ist der Fehlerbegriff durchaus angemessen.</p>
<ul>
<li><p>Systematische Messabweichungen: unter identischen Bedingungen konstante, d.&nbsp;h. nach Betrag und Vorzeichen gleiche, Verzerrung der Messergebnisse durch Abweichungen der Messgeräte. Beispielsweise:</p>
<ul>
<li>in Abhängigkeit von der Temperatur</li>
<li>fehlerhafte Kalibrierung</li>
<li>Alterung der Bauteile</li>
<li>die Art der Messung, z. B. Ablese- und Skalenfehler, Messintervall bei digitalen Messgeräten (<a href="https://de.wikipedia.org/wiki/Quantisierungsabweichung">Quantifizierungsfehler</a>)</li>
</ul></li>
<li><p>Zufällige Messabweichungen: statistische Streuung der Messwerte um ihren Erwartungswert. Beispielsweise:</p>
<ul>
<li>Stichprobenfehler</li>
<li>Ablesefehler</li>
</ul></li>
<li><p>Grobe Fehler: Verfälschen der Messergebnisse. Beispielsweise durch:</p>
<ul>
<li>falschen Versuchsaufbau</li>
<li>ungeeignete Messgeräte</li>
<li>falsches Ablesen, z. B. Missachtung der <a href="https://de.wikipedia.org/wiki/Einschwingzeit">Einschwingzeit</a> oder Unachtsamkeit, z. B. Mitwiegen des Gefäßes</li>
</ul></li>
</ul>
<p><span class="citation" data-cites="Hempel-2016 EdenGebhard-2024">[@Hempel-2016, S. 1-2; @EdenGebhard-2024, S. 17-18]</span></p>
<p>Bestimmte Tätigkeiten, wie das Ablesen, können mehreren Fehlerarten zugehörig sein:</p>
<ul>
<li>Unaufmerksames Ablesen und Flüchtigkeitsfehler sind grobe Fehler,</li>
<li>winkel- und positionsabhängige Fehler wie der <a href="https://de.wikipedia.org/wiki/Parallaxenfehler">Parallaxenfehler</a> sind systematische Abweichungen,</li>
<li>Fehler infolge des begrenzten Auflösungsvermögens des menschlichen Auges führen zu zufälligen Abweichungen.</li>
</ul>
<div id="tip-umgangmitfehlern" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;52.1: Umgang mit verschiedenen Arten von Messabweichungen
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Grobe Fehler: Betroffene Werte streichen und Messung wiederholen.</p></li>
<li><p>Systematische Messabweichungen: Systematische Messabweichungen werden, wenn sie bekannt sind, korrigiert.</p></li>
<li><p>Zufällige Messabweichungen: Die statistische Streuung von Messwerten um den Erwartungswert wird quantifiziert.</p></li>
</ol>
<p>Einige systematische und zufällige Messabweichungen können nur mit hohem Aufwand reduziert werden (genauere Messgeräte, größere Anzahl von Messvorgängen). Der Aufwand muss gegen den Gewinn an Genauigkeit abgewogen werden: Ist das Messergebnis mit der angegebenen Unsicherheit akzeptabel?</p>
<p>(<span class="citation" data-cites="Hempel-2016">@Hempel-2016</span>, S. 2)</p>
</div>
</div>
</section>
<section id="grundbegriffe-nach-din-1319" class="level2" data-number="52.3">
<h2 data-number="52.3" class="anchored" data-anchor-id="grundbegriffe-nach-din-1319"><span class="header-section-number">52.3</span> Grundbegriffe nach DIN 1319</h2>
<p>Die DIN 1319 normt Grundbegriffe und Verfahren der Messtechnik.</p>
<ul>
<li>Teil 1 DIN 1319-1 und Teil 2 DIN 1319-2 definieren Grundbegriffe der Messtechnik und für Messmittel.</li>
<li>Teil 3 DIN 1319-3 befasst sich mit der Auswertung von Messungen einer <em>einzelnen</em> Messgröße und deren Messunsicherheit. DIN 1319-3 wird auch angewendet, wenn die Messgröße mittels einer gegebenen Funktion aus anderen Größen berechnet wird (beispielsweise die Geschwindigkeit <span class="math inline">\(v\)</span> als Quotient der Strecke <span class="math inline">\(s\)</span> und der Zeit <span class="math inline">\(t\)</span>).</li>
<li>Teil 4 DIN 1319-4 befasst sich mit der Angabe von Messergebnissen und deren Messunsicherheit, wenn die Messgrößen aus anderen Größen berechnet werden, z. B. durch eine Ausgleichsrechung.</li>
</ul>
<p>DIN 1319-4 befasst sich mit der Berechnung einer Ergebnisgröße <span class="math inline">\(Y\)</span> durch eine Funktion wie z. B. die lineare Ausgleichsrechnung. Der Anwendungsfall des vorherigen Kapitels, die Federkonstante über den Regressionskoeffizienten <span class="math inline">\(\beta_1\)</span> zu bestimmen, wird in der Norm nicht behandelt. Dieser Teil der Norm wird hier deshalb nicht vorgestellt.</p>
<p>Das Lernziel dieses Kapitels besteht darin, dass Sie die folgende Grafik aus der DIN 1319 erklären können.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/fehlerarten-nach-DIN-1319.png" class="img-fluid figure-img" alt="Erläuternde Skizee aus der DIN 1319 zu den Grundbegriffen von Messungen."></p>
<figcaption>Messergebnis nach DIN 1319</figcaption>
</figure>
</div>
<p><span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 30]</span></p>
</div>
<p>&nbsp;</p>
<p>Die drei wichtigsten Grundbegriffe sind:</p>
<ol type="1">
<li>Messabweichung,</li>
<li>Messunsicherheit und</li>
<li>vollständiges Messergebnis.</li>
</ol>
<section id="messabweichung" class="level3" data-number="52.3.1">
<h3 data-number="52.3.1" class="anchored" data-anchor-id="messabweichung"><span class="header-section-number">52.3.1</span> Messabweichung</h3>
<p>Der in der Fehlerrechnung gebräuchliche Begriff des (Mess-)Fehlers meint im engeren Sinn die Messabweichung nach DIN 1319, also die <em>tatsächliche Abweichung</em> eines einzelnen Messwerts oder des arithmetischen Mittelwerts einer Messreihe (dem unberichtigten Messergebnis) vom wahren Wert der gemessenen Größe.</p>
<div id="imp-messabweichung" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important&nbsp;52.1: Messabweichung nach DIN 1319
</div>
</div>
<div class="callout-body-container callout-body">
<p>Die Messabweichung ist die: “Abweichung eines aus Messungen gewonnenen und der Meßgröße […] zugeordneten Wertes vom wahren Wert […]. Ist <span class="math inline">\(m\)</span> der der Meßgröße zugeordnete Wert und <span class="math inline">\(x_w\)</span> der wahre Wert, so ist die Meßabweichung des zugeordneten Wertes <span class="math inline">\(m - x_w\)</span> […].” <span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 12]</span></p>
</div>
</div>
<p>Die Messabweichung des <strong>unberichtigten Messergebnisses</strong> setzt sich additiv aus der zufälligen Messabweichung <span class="math inline">\(e_r\)</span> und der systematischen Messabweichung <span class="math inline">\(e_s\)</span> zusammen.</p>
<ul>
<li>Die systematische Messabweichung ist die Differenz aus dem Erwartungswert der Messung <span class="math inline">\(\mu\)</span> und dem wahrem Wert <span class="math inline">\(x_w\)</span>. Es gilt: <span class="math inline">\(e_s = \mu - x_w\)</span><br>
</li>
<li>Die systematische Messabweichung <span class="math inline">\(e_s\)</span> setzt sich aus einem bekannten <span class="math inline">\(e_{s,b}\)</span> und einem unbekannten Anteil <span class="math inline">\(e_{s,u}\)</span> zusammen.</li>
<li>Die bekannte, systematische Messabweichung <span class="math inline">\(e_{s,b}\)</span> wird mit entgegengesetzten Vorzeichen <span class="math inline">\(- e_{s,b}\)</span> <em>Korrektion</em> genannt.</li>
</ul>
<p>Das <strong>(berichtigte) Messergebnis</strong> <span class="math inline">\(\bar{x}_E\)</span> ist das um die bekannte, systematische Messabweichung <span class="math inline">\(e_{s,b}\)</span> berichtigte arithmetische Mittel einer Messreihe <span class="math inline">\(\bar{x}\)</span>, das als Schätzer des wahren Werts <span class="math inline">\(x_w\)</span> verwendet wird. <span class="math inline">\(\bar{x}_E = \bar{x} - e_{s,b}\)</span></p>
<p><span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 11-13]</span></p>
</section>
<section id="messunsicherheit" class="level3" data-number="52.3.2">
<h3 data-number="52.3.2" class="anchored" data-anchor-id="messunsicherheit"><span class="header-section-number">52.3.2</span> Messunsicherheit</h3>
<p>Der wahre Wert einer gemessenen Größe ist in der Regel unbekannt, sodass die tatsächliche Messabweichung ebenfalls nicht bekannt ist. Deshalb kann nur eine <em>aus den Messgrößen gewonnene Schätzung</em> der Messabweichung - die Messunsicherheit - angegeben werden. Der in der Fehlerrechnung gebräuchliche Begriff des (Mess-)Fehlers meint im weiteren Sinn die Messunsicherheit nach DIN 1319.</p>
<div id="imp-messunsicherheit" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important&nbsp;52.2: Messunsicherheit nach DIN 1319
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Kennwert, der aus Messungen […] gewonnen wird und zusammen mit dem Meßergebnis […] zur Kennzeichnung eines <strong>Wertebereiches</strong> für den wahren Wert der Meßgröße […] dient.” <span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 14, eigene Hervorhebung]</span></p>
<p>Während die Messabweichung ein Einzelwert ist, kennzeichnet die Messunsicherheit einen Wertebereich: “Die Meßunsicherheit ist von der Meßabweichung […] deutlich zu unterscheiden. Letztere ist nur die Differenz zwischen einem der Meßgröße zuzuordnenden Wert […] und dem wahren Wert. Die Meßabweichung kann gleich Null sein, ohne daß dies bekannt ist. Diese Unkenntnis drückt sich in einer Meßunsicherheit größer als Null aus.” <span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 3]</span></p>
</div>
</div>
<p>Die Messunsicherheit einer Messgröße <span class="math inline">\(Y\)</span> besteht einerseits aus der zufälligen Messabweichung <span class="math inline">\(e_r\)</span> und andererseits aus der Unsicherheit über die systematische Messabweichung <span class="math inline">\(u(e_s)\)</span>.</p>
<p><strong>zufällige Messabweichung</strong></p>
<p>Wird eine Messgröße <span class="math inline">\(Y = y(x)\)</span> durch mehrere, direkte Messungen bestimmt, so streuen die Messwerte <span class="math inline">\(x_i\)</span> zufällig um ihren Erwartungswert <span class="math inline">\(\mu\)</span> mit der Standardabweichung <span class="math inline">\(\sigma\)</span>. Der Erwartungswert <span class="math inline">\(\mu\)</span> und die Standardabweichung <span class="math inline">\(\sigma\)</span> sind in der Regel nicht bekannt und werden aus den Messwerten durch den arithmetischen Mittelwert <span class="math inline">\(\bar x\)</span> und die empirische Standardabweichung <span class="math inline">\(s_{n-1}\)</span> geschätzt. (siehe <a href="#sec-einleitung" class="quarto-xref"><span class="quarto-unresolved-ref">sec-einleitung</span></a>)</p>
<p>Als Unsicherheit der zufälligen Streuung wird die empirische Standardabweichung des Mittelwerts verwendet.</p>
<p><span class="math display">\[
u(\bar x) = \frac{s_{n-1}}{\sqrt{N}} ~ = ~ \sqrt{\frac{1}{N(N-1)} \sum_{i=1}^{N}(x_i - \bar{x})^2}
\]</span></p>
<p><span class="citation" data-cites="DIN1319-3">[@DIN1319-3, Gleichung (4), S. 5, Notation angepasst]</span></p>
<p><strong>systematische Messabweichung</strong></p>
<p>Die systematische Messabweichung <span class="math inline">\(e_s\)</span> setzt sich aus einem bekannten Anteil <span class="math inline">\(e_{s,b}\)</span> und einem unbekannten Anteil <span class="math inline">\(e_{s,u}\)</span> zusammen. Da der unbekannte Anteil nicht bestimmt werden kann, wird die gesamte systematische Messabweichung über die bekannte systematische Messabweichung <span class="math inline">\(e_{s,b}\)</span> geschätzt. Daraus ergibt sich eine Unsicherheit über die tatsächliche gesamte systematische Messabweichung <span class="math inline">\(u(e_{s})\)</span>. Diese Unsicherheit besteht auch, wenn die bekannte systematische Messabweichung <span class="math inline">\(e_{s,b}\)</span> Null ist, weil der unbekannte Anteil <span class="math inline">\(e_{s,u}\)</span> ungleich Null sein kann.</p>
<p>In der DIN 1319 werden zwei Fälle unterschieden, je nachdem, ob die Unsicherheit <span class="math inline">\(u(e_{s})\)</span> als vernachlässigbar eingeschätzt wird oder nicht. In diesem Kapitel gehen wir von einer vernachlässigbaren Unsicherheit <span class="math inline">\(u(e_{s})\)</span> aus (Für den zweiten Fall siehe Beispiel).</p>
<div id="nte-unsicherheit" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.1: <span class="math inline">\(u(e_{s})\)</span> nicht vernachlässigbar
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Für den Fall, dass die Unsicherheit der systematischen Messabweichung nicht als vernachlässigbar angesehen wird, verweist die DIN 1319-3 auf Berechnungsregeln in Abschnitt 6.2.5 auf die wir hier nicht eingehen. (<span class="citation" data-cites="DIN1319-3">@DIN1319-3</span>, S. 5-6)</p>
<p>Die Messunsicherheit des berichtigten Messergebnisses berechnet sich aus der quadratischen Kombination der Unsicherheiten der zufälligen und der systematischen Messabweichung.</p>
<p><span class="math display">\[
u(y) = \sqrt{u^2(\bar x) + u^2(e_s)}
\]</span></p>
<p><span class="citation" data-cites="DIN1319-3">[@DIN1319-3, Gleichung (8), S. 6, Notation angepasst]</span></p>
<div id="wrn-notation2" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;52.1: Notation in der DIN 1319
</div>
</div>
<div class="callout-body-container callout-body">
<p>In der DIN wird die zufällige Messabweichung statt mit <span class="math inline">\(u^2(\bar x)\)</span> mit <span class="math inline">\(u^2(x_1)\)</span> und die Unsicherheit der systematischen Messabweichung statt mit <span class="math inline">\(u^2(e_s)\)</span> mit <span class="math inline">\(u^2(x_2)\)</span> notiert.</p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="vollständiges-messergebnis" class="level3" data-number="52.3.3">
<h3 data-number="52.3.3" class="anchored" data-anchor-id="vollständiges-messergebnis"><span class="header-section-number">52.3.3</span> Vollständiges Messergebnis</h3>
<p>Das <strong>berichtigte Messergebnis</strong> <span class="math inline">\(\bar{x}_E = y\)</span> (in der DIN 1319 wechselt die Notation von <span class="math inline">\(\bar{x}_E\)</span> zu <span class="math inline">\(y\)</span>) berechnet sich durch die Korrektion der bekannten systematischen Messabweichung:</p>
<p><span class="math display">\[
y = \bar x - e_{s,b}
\]</span></p>
<p><span class="citation" data-cites="DIN1319-3">[@DIN1319-3, Gleichung (7), S. 6, Notation angepasst]</span></p>
<p>Das <strong>vollständige Messergebnis</strong> <span class="math inline">\(Y\)</span> besteht aus dem berichtigten Messergebnis und einer Angabe über die Unsicherheit der Messung z. B. in der Form:</p>
<p><span class="math display">\[
Y = y \pm u(y)
\]</span></p>
<p><span class="citation" data-cites="DIN1319-3">[@DIN1319-3, Gleichung (9), S. 6]</span></p>
<p><em>Zusätzlich</em> zum vollständigen Messergebnis kann ein Vertrauensbereich (auch: Vertrauensintervall oder Konfidenzintervall) angegeben werden. Der Berechnung von Konfidenzintervallen haben wir im Kapitel <a href="#sec-normalverteilung" class="quarto-xref"><span class="quarto-unresolved-ref">sec-normalverteilung</span></a> vorgegriffen.</p>
<p><span class="math display">\[
y - t \cdot u(y) \le Y \le y + t \cdot u(y)
\]</span></p>
<p><span class="citation" data-cites="DIN1319-3">[@DIN1319-3, Gleichung (14), S. 7]</span></p>
<p>Die Wahl eines Vertrauensbereichs ist Ermessenssache. Die DIN 1319 formuliert dazu: “Es ist üblich, das Vertrauensniveau (<span class="math inline">\(1 - \alpha\)</span>) in Prozent anzugeben, wobei meist <span class="math inline">\(\alpha = 0,05\)</span> (Vertrauensniveau: 95 %) benutzt wird.” <span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 17]</span> “Dieses Vertrauensniveau von 95 % sollte verwendet werden, aber kein höheres.” <span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 7]</span></p>
<p>So ergibt sich beispielsweise:</p>
<p><span class="math display">\[
y - t_{\alpha / 2} \cdot \frac{s_{n-1}}{\sqrt{n}} \le Y \le y + t_{\alpha / 2} \cdot \frac{s_{n-1}}{\sqrt{n}}
\]</span></p>
<div id="wrn-notation1" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;52.2: Notation in der DIN 1319
</div>
</div>
<div class="callout-body-container callout-body">
<p>In der DIN wird der arithmetische Mittelwert einer Messreihe statt mit <span class="math inline">\(\bar{x}\)</span> mit <span class="math inline">\(\bar{v}\)</span> notiert.</p>
</div>
</div>
</section>
<section id="übersicht" class="level3" data-number="52.3.4">
<h3 data-number="52.3.4" class="anchored" data-anchor-id="übersicht"><span class="header-section-number">52.3.4</span> Übersicht</h3>
<p>In der DIN 1319 werden eine Reihe weiterer Begriffe definiert, die im folgenden Kasten zusammen mit den wichtigsten Grundbegriffen zusammengestellt wurden.</p>
<div id="imp-DIN1319" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important&nbsp;52.3: Grundbegriffe nach DIN 1319
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Messabweichung</strong>: “Abweichung eines aus Messungen gewonnenen und der Meßgröße […] zugeordneten Wertes vom wahren Wert […]. Ist <span class="math inline">\(m\)</span> der der Meßgröße zugeordnete Wert und <span class="math inline">\(x_w\)</span> der wahre Wert, so ist die Meßabweichung des zugeordneten Wertes <span class="math inline">\(m - x_w\)</span> […].” <span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 12]</span></p>
<ul>
<li>Die Messabweichung des <strong>unberichtigten Messergebnisses</strong> setzt sich additiv aus der zufälligen Messabweichung <span class="math inline">\(e_r\)</span> und der systematischen Messabweichung <span class="math inline">\(e_s\)</span> zusammen.</li>
<li>Die systematische Messabweichung <span class="math inline">\(e_s\)</span> setzt sich aus einem bekannten <span class="math inline">\(e_{s,b}\)</span> und einem unbekannten Anteil <span class="math inline">\(e_{s,u}\)</span> zusammen.</li>
<li>Die systematische Messabweichung ist die Differenz aus Erwartungswert <span class="math inline">\(\mu\)</span> und wahrem Wert <span class="math inline">\(x_w\)</span>. <span class="math inline">\(e_s = \mu - x_w\)</span></li>
<li>Die bekannte, systematische Messabweichung <span class="math inline">\(e_{s,b}\)</span> wird mit entgegengesetzten Vorzeichen <span class="math inline">\(- e_{s,b}\)</span> <em>Korrektion</em> genannt.</li>
</ul>
<p>Das <strong>Messergebnis</strong> <span class="math inline">\(\bar{x}_E\)</span> ist das um die bekannte, systematische Messabweichung <span class="math inline">\(e_{s,b}\)</span> berichtigte arithmetische Mittel einer Messreihe <span class="math inline">\(\bar{x}\)</span>, das als Schätzer des Erwartungswerts <span class="math inline">\(\mu\)</span> verwendet wird.<br>
<span class="math inline">\(\bar{x}_E = \bar{x} - e_{s,b}\)</span></p>
<p><span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 11-13]</span></p>
<p><strong>Messunsicherheit</strong> <span class="math inline">\(u\)</span> oder <span class="math inline">\(u(y)\)</span>: “Kennwert, der aus Messungen […] gewonnen wird und zusammen mit dem Meßergebnis […] zur Kennzeichnung eines Wertebereichs für den wahren Wert der Meßgröße […] dient.” <span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 14]</span></p>
<ul>
<li><p><strong>Standardmessunsicherheit</strong> oder kurz Standardunsicherheit wird verwendet, wenn die Messunsicherheit durch eine Standardabweichung ausgedrückt wird. <span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 3]</span></p></li>
<li><p><strong>erweiterte Messunsicherheit</strong> <span class="math inline">\(U(y) = k \cdot u(y)\)</span>: Wertebereich, der den wahren Wert der Messgröße wahrscheinlich enthält. Der Erweiterungsfaktor <span class="math inline">\(k\)</span> sollte zwischen 2 und 3 festgelegt werden, vorzugsweise wird <span class="math inline">\(k = 2\)</span> verwendet. Der Erweiterungsfaktor <span class="math inline">\(k\)</span> ist mitzuteilen, damit die Standardmessunsicherheit <span class="math inline">\(u(y) = U(y) / k\)</span> ermittelt werden kann. <span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 7]</span><br>
<em>Hinweis: Die erweiterte Messunsicherheit unterscheidet sich vom Konfidenzintervall dadurch, dass keine Normalverteilung unterstellt wird - es ist schlicht ein Faktor, ‘um auf Nummer sicher zu gehen’, dass der wahre Wert vom angegebenen Bereich eingeschlossen wird</em>.</p></li>
</ul>
<p>Das <strong>vollständige Messergebnis</strong> ist das Messergebnis mit quantitativen Angaben zur Messunsicherheit <span class="math inline">\(u\)</span>. <span class="math inline">\(x = \bar{x}_E \pm u\)</span>. <span class="citation" data-cites="DIN1319-1">[@DIN1319-1, S. 16]</span></p>
<ul>
<li><p>Der <strong>Vertrauensbereich</strong> <span class="math inline">\(\bar x - t \cdot u(y) \le Y \le y + t \cdot u(y)\)</span> kann zusätzlich zum vollständigen Messergebnis angegeben werden.</p>
<ul>
<li>Ist die systematische Messabweichung bekannt und korrigiert worden, dann liegt der wahre Wert der Messgröße <span class="math inline">\(Y\)</span> innerhalb des Vertrauensbereichs.</li>
<li>Wenn die systematische Messabweichung nicht bekannt ist, liegt der Erwartungswert <span class="math inline">\(\mu\)</span> der Verteilung im Vertrauensbereich. <span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 7]</span></li>
</ul>
<p><em>Hinweis: In der DIN wird der arithmetische Mittelwert einer Messreihe statt mit <span class="math inline">\(\bar{x}\)</span> mit <span class="math inline">\(\bar{v}\)</span> geschrieben</em>.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="absolute-und-relative-fehler" class="level2" data-number="52.4">
<h2 data-number="52.4" class="anchored" data-anchor-id="absolute-und-relative-fehler"><span class="header-section-number">52.4</span> Absolute und relative Fehler</h2>
<p>In der Fehlerrechnung werden absolute und relative <em>Fehler</em> unterschieden. Hier sollte besser von absoluter und relativer Messunsicherheit gesprochen werden.</p>
<ul>
<li><p>Die <strong>absolute Messunsicherheit</strong> <span class="math inline">\(u\)</span> wird in der Einheit der gemessenen Größe angegebenen: <span class="math inline">\(u(m) = 0,2 ~ kg\)</span>. Das vollständige Messergebnis lautet: <span class="math inline">\(m = 5,0 \pm 0,2 ~ kg\)</span> oder <span class="math inline">\(m = 5,0 ~ kg \pm 0,2 ~ kg\)</span>.</p></li>
<li><p>Die <strong>relative Messunsicherheit</strong> <span class="math inline">\(u_{rel}(m) = \frac{u(m)}{ | m | }\)</span> wird entweder als Produkt in der Form <span class="math inline">\(m \cdot (1 \pm \frac{u(x)}{| m |})\)</span> angegeben. Bspw.:</p>
<p><span class="math inline">\(m = 5,0 ~ kg \cdot (1 \pm \frac{0,2 ~ kg}{5,0 ~ kg}) = 5,0 ~ kg \cdot (1 \pm 0,04)\)</span></p>
<p>Alternativ wird die relative Messunsicherheit in Prozent <span class="math inline">\(u_{rel}(m) = \frac{u(m)}{| m |} \cdot 100 ~ \%\)</span> angegeben. Bspw.:</p>
<p><span class="math inline">\(m = 5,0 ~ kg \pm 4 ~ \%\)</span>.</p></li>
</ul>
<p><span class="citation" data-cites="DIN1319-1 DIN1319-3">[@DIN1319-1, S. 9-10, 16; @DIN1319-3, S. 10]</span></p>
<div id="wrn-notation" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;52.3: (Alternative) Notationen
</div>
</div>
<div class="callout-body-container callout-body">
<p>In der DIN 1319 werden Messabweichungen mit <span class="math inline">\(e\)</span>, die Messunsicherheit mit <span class="math inline">\(u\)</span> notiert. In der Literatur zur Fehlerrechnung wird zumeist der Begriff des (Mess-)Fehlers verwendet. Die Notation ist allerdings uneinheitlich.</p>
<ul>
<li><p>Der absolute Fehler wird häufig mit <span class="math inline">\(\epsilon x\)</span> (epsilon x) notiert. Üblich ist aber auch die Notation mit <span class="math inline">\(\Delta x\)</span> (Delta), (beispielsweise <span class="citation" data-cites="HS-Aalen-2016 Dinter-2011 SchrüferEtAl2022">[@HS-Aalen-2016; @Dinter-2011; @SchrüferEtAl2022]</span>. <span class="math inline">\(\Delta\)</span> wird aber ebenfalls für den Größtfehler verwendet.</p></li>
<li><p>Der relative Fehler wird auch mit <span class="math inline">\(\delta x\)</span> (delta x) notiert, bspw: <span class="math inline">\(\delta x = 4 \%\)</span>.</p></li>
</ul>
</div>
</div>
</section>
<section id="größtfehler" class="level2" data-number="52.5">
<h2 data-number="52.5" class="anchored" data-anchor-id="größtfehler"><span class="header-section-number">52.5</span> Größtfehler</h2>
<p>Systematische Messabweichungen <span class="math inline">\(e(x)_{s}\)</span> bewirken eine einseitige Verzerrung des Messergebnisses, sodass der Messwert immer zu hoch oder zu niedrig ausfällt. Zufällige Messabweichungen <span class="math inline">\(e(x)_{r}\)</span> führen unkontrolliert mal zum Über-, mal zum Unterschätzen des Messwerts.</p>
<p>In der Regel werden sich die verschiedenen Messabweichungen teilweise ausgleichen. Als <strong>Größtfehler</strong> wird der ungünstigste Fall bezeichnet, bei dem sich alle Messabweichungen jeweils um ihren maximalen (oder minimalen) Wert gegenseitig verstärken, sodass der Messwert die maximal mögliche Abweichung vom (unbekannten) tatsächlichen Wert aufweist. Der <strong>Größtfehler</strong> wird als <span class="math inline">\(\Delta x\)</span> (Delta x) notiert.</p>
<p>Der Größtfehler einer Messreihe für eine Größe wird ermittelt, indem man die Beträge der einzelnen Messabweichungen addiert.</p>
<p><span class="math display">\[
\Delta x = | e(x)_{s} | + | e(x)_{r} |
\]</span></p>
<p>Da Messungen bei groben Fehlern als ungültig anzusehen sind, entfällt der Anteil grober Fehler <span class="math inline">\(| e(x)_{grob} |\)</span>.</p>
<p>(<span class="citation" data-cites="EdenGebhard-2024">@EdenGebhard-2024</span>, S. 35-36)</p>
<p>Werden mehrere Größen betrachtet, addieren sich die Größtfehler der beteiligten Größen zum Größtfehler der Ergebnisgröße. So gilt für eine Größe <span class="math inline">\(Y = f(x_1, x_2)\)</span>: <span class="math display">\[
\Delta y = \Delta x_1 + \Delta x_2
\]</span></p>
<div id="tip-welcherfehler" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;52.2: Größtfehler
</div>
</div>
<div class="callout-body-container callout-body">
<p>Der Größtfehler ist keine genormte Angabe nach DIN 1319, sondern eine vereinfachte Form der Fehlerabschätzung und überschätzt die wahrscheinliche Messunsicherheit.</p>
<p>“Für viele Betrachtungen, speziell in den Grundlagenpraktika der ersten Semester in technischen, naturwissenschaftlichen und ingenieurmäßigen Studiengängen, reicht es aus, den maximalen Fehler (<em>absoluter Größtfehler</em>) zu bestimmen.” (<span class="citation" data-cites="EdenGebhard-2024">@EdenGebhard-2024</span>, S. 35)</p>
</div>
</div>
</section>
<section id="signifikante-stellen" class="level2" data-number="52.6">
<h2 data-number="52.6" class="anchored" data-anchor-id="signifikante-stellen"><span class="header-section-number">52.6</span> Signifikante Stellen</h2>
<p>Bei der Angabe des vollständigen Messergebnisses ist die Anzahl der signifikanten oder zuverlässig bekannten Stellen zu beachten.</p>
<div id="imp-signif" class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important&nbsp;52.4: signifikante Stellen
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Jede zuverlässig bekannte Stelle mit Ausnahme der Nullen, die die Position des Dezimalkommas angeben, wird signifikante Stelle genannt.” <span class="citation" data-cites="EdenGebhard-2024">[@EdenGebhard-2024, S. 24]</span></p>
<p>“Gerundete numerische Unsicherheitwerte sind <strong>mit zwei (oder bei Bedarf mit drei) signifikanten Ziffern</strong> anzugeben. <strong>Sie sind aufzurunden</strong>. Das Meßergebnis ist an derselben Stelle wie die zugehörige Unsicherheit zu runden, z.B. <span class="math inline">\(y = 245,5716 ~ mm\)</span> auf <span class="math inline">\(y = 245,57 ~ mm\)</span>, wenn <span class="math inline">\(u(y) = 0,4528 ~ mm\)</span> auf <span class="math inline">\(u(y) = 0,46 ~ mm\)</span> aufgerundet wird.” <span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 6, eigene Hervorhebung]</span></p>
</div>
</div>
<p>Beispielsweise liegen die im vorherigen Kapitel verwendeten Abstandsmessungen im Format <span class="math inline">\(153,29\)</span> vor, die Messwerte weisen also 5 signifikante Stellen auf. Für den arithmetischen Mittelwert einer Messreihe <span class="math inline">\(153,008889\)</span> gelten deshalb ebenfalls 5 signifikante Stellen. Es wird an der ersten nicht mehr signifikanten Stelle gerundet, sodass der arithmetische Mittelwert mit <span class="math inline">\(153,01\)</span> angegeben wird.</p>
<p>Die Anzahl signifikanter Stellen ist allerdings nicht immer zuverlässig zu bestimmen. Es gilt:</p>
<ol type="1">
<li>Alle Ziffern ungleich Null sind immer signifikant.</li>
<li>Führende Nullen sind niemals signifikante Stellen. Beispielsweise hat 0012 km 2 signifikante Stellen. 0,001 mm hat eine signifikante Stelle.</li>
<li>Nullen am Ende einer Zahl sind signifikant, wenn sie sich rechts vom Dezimaltrennzeichen befinden, bspw: 12,100 km hat 5 signifikante Stellen.</li>
<li>Nullen, die sich am Ende einer Zahl ohne Komma befinden, können signifikant sein. 1200 m kann zwei oder vier signifikante Stellen haben.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
signifikante Stellen und wissenschaftliches Runden
</div>
</div>
<div class="callout-body-container callout-body">
<p>Angaben zur Messunsicherheit werden zwar aufgerundet. Trotzdem an dieser Stelle: Kennen Sie den Unterschied zwischen kaufmännischem und wissenschaftlichem Runden?</p>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/s0gPyypiGOs" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Runden und signifikante Stellen (Vorkurs Mathematik) von Edmund Weitz ist abrufbar auf <a href="https://www.youtube.com/watch?v=q2iZDtotiM0">YouTube</a>. 2019</p>
<p>Python rundet wissenschaftlich:</p>
<div id="b25f5290" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">round</span>(<span class="fl">2.5</span>), <span class="bu">round</span>(<span class="fl">3.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 4</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="methoden-der-fehlerrechnung" class="level2" data-number="52.7">
<h2 data-number="52.7" class="anchored" data-anchor-id="methoden-der-fehlerrechnung"><span class="header-section-number">52.7</span> Methoden der Fehlerrechnung</h2>
<p>Das Ziel der Fehlerrechnung ist es, Unsicherheitsintervalle für die gemessene Größe zu ermitteln. Dafür stehen verschiedene Methoden zur Verfügung:</p>
<ol type="1">
<li>Fehlerabschätzung,</li>
<li>Fehlerstatistik und</li>
<li>Fehlerfortpflanzung.</li>
</ol>
<p>Bei der Auswahl der Methode besteht ein Ermessensspielraum. (<span class="citation" data-cites="Hempel-2016">@Hempel-2016</span>, S. 2) Für Gebrauchsmessungen reicht es aus, die Unsicherheit im Prozentbereich anzugeben. Im Eichwesen oder beim Vergleich mit einem <a href="https://de.wikipedia.org/wiki/Normal">Normal</a> werden genauere Angaben benötigt. <span class="citation" data-cites="SchrüferEtAl2022">[@SchrüferEtAl2022, S. 33]</span></p>
<p>Die Auswahl der geeigneten Methode hängt auch von den zur Verfügung stehenden Informationen ab. Beispielsweise hängt die im vorherigen Kapitel ermittelte Federkonstante von drei Größen ab:</p>
<ol type="1">
<li><p>der Masse <span class="math inline">\(m\)</span>, die mit einer Küchenwaage ermittelt wurde, deren Ablesegenauigkeit mit <span class="math inline">\(e_r(m) = 0,5 g = 0,0005 ~ kg\)</span> geschätzt wird.</p></li>
<li><p>dem Abstand zum Gewicht bzw. nach der Aufbereitung der Daten der Ausdehnung der Feder <span class="math inline">\(\Delta x\)</span>, die mit einem elektronischen Abstandssensor und einem Arduino ermittelt wurden (Ultrasonic Ranging Module HC - SR04).</p>
<ul>
<li>Die Ablesegenauigkeit des Messsystems beträgt eine Einheit der Messauflösung, also <span class="math inline">\(e_{r} = 0,01 ~ cm = 0,0001 ~ m\)</span>.</li>
<li>Die Messabweichung des Messsystems beträgt laut Datenblatt bis zu 3 mm, die symmetrisch zu verstehen ist, also <span class="math inline">\(e_{r} = 3 ~ mm = 0,003 ~ m\)</span>.</li>
<li>Die zufällige Komponente der Messabweichung beträgt also <span class="math inline">\(e_r(x) = 0,0001 ~ m + 0,003 ~ m = 0,0031 ~ m\)</span></li>
</ul></li>
<li><p>der statistischen Schätzung der Federkonstante <span class="math inline">\(k = \frac{m \cdot g}{\Delta x} = 33,019 \pm 0,378\)</span> bzw. im festgelegten Vertrauensintervall <span class="math inline">\(k_{95\%} = 32,269 ≤ 33,019 ≤ 33,769\)</span>.</p></li>
</ol>
<div id="wrn-formelzeichen" class="callout callout-style-simple callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;52.4: Formelzeichen und Einheiten
</div>
</div>
<div class="callout-body-container callout-body">
<p>Im Folgenden werden identische Zeichen für Sekunde und Strecke <span class="math inline">\(s\)</span>, Masse und Meter <span class="math inline">\(m\)</span>, Gramm und die Konstante <span class="math inline">\(g\)</span> sowie <span class="math inline">\(\Delta\)</span> für die Veränderung einer Größe und den Größtfehler verwendet. Die Formeln sollten also mit großer Aufmerksamkeit gelesen werden.</p>
</div>
</div>
<section id="fehlerabschätzung" class="level3" data-number="52.7.1">
<h3 data-number="52.7.1" class="anchored" data-anchor-id="fehlerabschätzung"><span class="header-section-number">52.7.1</span> 1. Fehlerabschätzung</h3>
<p>Die Fehlerabschätzung wird verwendet, wenn</p>
<ul>
<li><strong>eine Größe</strong></li>
<li><strong>nur einmal</strong></li>
</ul>
<p>gemessen wird.</p>
<p>Da der wahre Wert einer Messgröße unbekannt ist, bezweckt die Fehlerabschätzung, die maximal mögliche Abweichung des Messwerts vom tatsächlichen Wert, also den <strong>Größtfehler</strong>, zu bestimmen. Bei einer einmaligen Messung gibt es keine statistische Komponente. In die Fehlerabschätzung eines einzelnen Messwerts gehen deshalb ein:</p>
<ul>
<li>die Garantiefehlergrenze des Messgerätes, die vom Hersteller auf dem Gerät oder in der Bedienungsanleitung angegeben ist (siehe Beispiel), also die bekannte systematische Messabweichung <span class="math inline">\(e_{s,b}\)</span>, und</li>
<li>ein abgeschätzter Anteil, der sich nach den konkreten Bedingungen des Experiments, etwa der Skalenteilung des Messgerätes oder den Ablesebedingungen richtet. Dieser Anteil kann also aus einem systematischen Anteil (bspw. eine analoge Skala konnte nur aus einem Winkel abgelesen werden) und einem zufälligen Anteil (bspw. Ablesegenauigkeit des Messgeräts) bestehen.</li>
</ul>
<p>Der Größtfehler <span class="math inline">\(\Delta x\)</span> ergibt sich aus der Addition der Beträge der bekannten systematischen Messabweichung und der geschätzten zufälligen Messabweichung: <span class="math inline">\(\Delta x = |e(x)_{s,b}| + |e(x)_{r}|\)</span>.</p>
<p>(<span class="citation" data-cites="Hempel-2016">@Hempel-2016</span>, S. 3)</p>
<section id="aufgabe-temperaturmessung" class="level4" data-number="52.7.1.1">
<h4 data-number="52.7.1.1" class="anchored" data-anchor-id="aufgabe-temperaturmessung"><span class="header-section-number">52.7.1.1</span> Aufgabe Temperaturmessung</h4>
<p>Mit einem digitalen Thermometer und einem thermoelektrischen Element vom Typ K wurde die Temperatur <span class="math inline">\(T = 112,1 ~ °C\)</span> gemessen. Welche systematischen und zufälligen Messabweichungen sind bekannt und können angegeben werden (siehe Beispiel)?</p>
<div id="nte-thermometer" class="callout callout-style-default callout-note callout-titled" data-layout-ncol="2">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.2: Garantiefehlergrenze Thermometer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../../skript/00-bilder/thermometer.jpg" class="img-fluid figure-img" alt="Herstellerangaben zum Thermoemeter 53/54 II B"></p>
<figcaption>Thermometer</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../../skript/00-bilder/thermometerspecifications.jpg" class="img-fluid figure-img" alt="Vergrößerter Ausschnitt aus den Herstellerangaben zum Thermoemeter 53/54 II B - dieser zeigt die Angaben zur Messabweichung."></p>
<figcaption>Spezifikationen</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div id="tip-skalengenauigkeit" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;52.3: Halber oder ganzer Skalenstrich?
</div>
</div>
<div class="callout-body-container callout-body">
<div class="border">
<p>Messgeräte mit digitaler Anzeige machen es leicht: Die Ablesegenauigkeit beträgt eine Skaleneinheit. Bei Messgeräten mit analoger Anzeige ist es Ermessenssache, welche Messgenauigkeit Sie angeben können bzw. möchten.</p>
<p>Sind Sie sich absolut sicher, dass Sie zwischen “genau auf dem Strich” und “zwischen zwei Strichen” unterscheiden können, beträgt Ihr Ablesefehler einen halben Skalenstrich. Sind Sie sich nicht sicher, beträgt Ihr Ablesefehler einen ganzen Skalenstrich.</p>
<p>(<a href="https://www.physik.uni-jena.de/pafmedia/9072/fehlerrechnungleichtgemachtpdf.pdf">Fehlerrechnung leicht gemacht, FSU Jena</a>)</p>
</div>
</div>
</div>
<div id="tip-thermometer" class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip&nbsp;52.4: Musterlösung Temperaturmessung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>systematische Messabweichung</strong></p>
<p>Die absolute Messabweichung beträgt <span class="math inline">\(u(T) = 0,3 ~ °C\)</span>. Die relative Messabweichung beträgt <span class="math inline">\(0,05 ~ \%\)</span>. Das bedeutet:</p>
<p><span class="math inline">\(\frac{u(T)}{112,1 °C} \cdot 100 ~ \% = 0,05 ~ \%\)</span></p>
<p><span class="math inline">\(\frac{u(T)}{112,1 °C} \cdot 100 = 0,05\)</span></p>
<p><span class="math inline">\(u(T) = 0,05 \cdot \frac{112,1 °C}{100}\)</span></p>
<p><span class="math inline">\(u(T) = 0,05605 °C\)</span></p>
<p>Die bekannte systematische Messabweichung beträgt also:</p>
<p><span class="math inline">\(e(T)_{s,b} = 0,3 ~ °C+ 0,05605 ~ °C = 0,35605 ~ °C\)</span></p>
<p><strong>zufällige Messabweichung</strong></p>
<p>Die zufällige Messabweichung beträgt eine Skaleneinheit, also:</p>
<p><span class="math inline">\(e(T)_{r} = 0,1 ~ °C\)</span></p>
<p><strong>Größtfehler</strong></p>
<p>Der Größtfehler beträgt:</p>
<p><span class="math inline">\(\Delta T = |e(T)_{s,b}| + |e(T)_{r}|\)</span></p>
<p>Die Messunsicherheit ist auf zwei Stellen aufzurunden:</p>
<p><span class="math inline">\(\Delta T = |0,35605 °C| + |0,1 ~ °C| = 0,45605 ~ °C \approx 0,46 °C\)</span></p>
<p>Das vollständige Messergebnis lautet also <span class="math inline">\(T = 112,1 \pm 0,46 ~ °C\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="beispiel-messbedingungen" class="level4" data-number="52.7.1.2">
<h4 data-number="52.7.1.2" class="anchored" data-anchor-id="beispiel-messbedingungen"><span class="header-section-number">52.7.1.2</span> Beispiel Messbedingungen</h4>
<p>Was ist mit den konkreten Bedingungen eines Messvorgangs gemeint? Das soll mit zwei einfachen Messvorgängen demonstriert werden.</p>
<p><strong>Hier können Sie mitmachen!</strong></p>
<p>Sie benötigen:</p>
<ul>
<li>ein geeignetes Messinstrument, z. B. ein Lineal, und</li>
<li>eine Münze (idealerweise 1-Euro-Münze).</li>
</ul>
<p>Im ersten Messvorgang soll der Durchmesser der 1-Euro-Münze bestimmt werden.</p>
<div id="nte-münze" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.3: Erster Messvorgang Münze
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Die Messung wird mit einem <a href="https://de.wikipedia.org/wiki/Nonius">Messschieber mit Nonius</a> 0,05 mm nach DIN 862 durchgeführt. Die DIN 862 normiert symmetrische Fehlergrenzen von Messschiebern. Die Fehlergrenze ist abhängig von der Skalengenauigkeit des Messschiebers sowie von der gemessenen Länge und ist aus einer Tabelle abzulesen. (DIN 862 wurde 2011 durch DIN EN ISO 13385-1 ersetzt, in der der Begriff der Abweichung verwendet wird. Die DIN 862 ist aber auf dem Messschieber aufgedruckt.)</p>
<p>Messwert: <span class="math inline">\(x = 23,25 ~ mm\)</span></p>
<ul>
<li>Die Skaleneinteilung ist 0,05 ~ mm, die zufällige Ableseabweichung <span class="math inline">\(e_r\)</span> beträgt also <span class="math inline">\(\pm 0,025 mm\)</span>.</li>
<li>Die DIN 862 normiert Fehlergrenzen, die abhängig von der gemessenen Länge zunehmen, mindestens aber 50 <span class="math inline">\(\mu m\)</span> oder 0,05 mm betragen. Für den Messwert 23,25 mm gilt somit als bekannte systematische Messabweichung <span class="math inline">\(e_{s,b} = \pm 0,05 ~ mm\)</span>.</li>
</ul>
<p>Aus der Summe der Beträge ergibt sich der Größtfehler: <span class="math inline">\(\Delta x = |0,05| ~ mm + |0,025| ~ mm = 0,075 ~ mm\)</span>.</p>
<p>Das vollständige Messergebnis, bestehend aus dem Messwert und der Messunsicherheit lautet also: <span class="math inline">\(23,25 ± 0,075 ~ mm\)</span>. Der relative Größtfehler beträgt: <span class="math inline">\(23,25 ~ mm ± 0,32\%\)</span>.</p>
</div>
</div>
</div>
<p>Im zweiten Messvorgang soll die Länge des Daumens bestimmt werden. (<a href="https://de.wikipedia.org/wiki/Daumen">Der Daumen besteht anatomisch aus nur 2 Fingergliedknochen</a>)</p>
<div id="nte-daumen" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.4: Zweiter Messvorgang Daumen
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Die Messung wird erneut mit dem Messschieber durchgeführt.</p>
<p>Messwert: <span class="math inline">\(x = 64,70 ~ mm\)</span></p>
<ul>
<li>Die Skaleneinteilung ist 0,05 mm, die zufällige Ableseabweichung beträgt also <span class="math inline">\(\pm 0,025 ~ mm\)</span>.</li>
<li>Die von der DIN 862 für gemessene Längen zwischen 50 und 300 mm normierte Fehlergrenze beträgt 50 <span class="math inline">\(\mu m\)</span> oder 0,05 mm. Für den Messwert 64,7 mm gilt somit die Fehlergrenze <span class="math inline">\(\pm  0,05 ~ mm\)</span>.</li>
<li>zusätzlich wird eine symmetrische Messabweichung von 3 mm veranschlagt, da
<ul>
<li>das Messgerät nicht gerade angesetzt,</li>
<li>die Daumenwurzel nicht exakt lokalisiert und</li>
<li>die elastische Fingerkuppe nicht fixiert werden konnte.</li>
</ul></li>
</ul>
<p>Aus der Summe der Beträge ergibt sich der Größtfehler <span class="math inline">\(\Delta x = |0,025| ~ mm + |0,05| ~ mm + |3| ~ mm = 3,075 ~ mm \approx 3,08 ~ mm\)</span>.</p>
<p>Das Messergebnis, bestehend aus dem Messwert und dem Fehlerintervall lautet also: <span class="math inline">\(64,70 ± 3,08 ~ mm\)</span>. Der relative Größtfehler beträgt: <span class="math inline">\(64,70 ~ mm ± 4,76 \%\)</span>.</p>
</div>
</div>
</div>
</section>
</section>
<section id="fehlerstatistik" class="level3" data-number="52.7.2">
<h3 data-number="52.7.2" class="anchored" data-anchor-id="fehlerstatistik"><span class="header-section-number">52.7.2</span> 2. Fehlerstatistik</h3>
<p>Die Fehlerstatistik wird verwendet, wenn</p>
<ul>
<li><strong>eine Größe</strong></li>
<li><strong>mehrfach</strong></li>
</ul>
<p>gemessen wird.</p>
<p>Die Fehlerstatistik ist nur dann als zuverlässig anzusehen, wenn die Messabweichung zufällig ist, die Messwerte also betragsmäßig und mit wechselndem Vorzeichen streuen. Dann ist die Messabweichung in der ermittelten Standardabweichung enthalten. Liegt jedoch eine bekannte, systematische Messabweichung vor, muss das Messergebnis entsprechend korrigiert werden <span class="math inline">\(\bar x_E = \bar x - e_{s,b}\)</span>.</p>
<p>Der Fehlerstatistik haben wir in vorausgehenden Kapiteln mit der statistischen Beschreibung der empirischen Streuung des Mittelwerts vorgegriffen. Zur Wiederholung:</p>
<ol type="1">
<li>Legen Sie ein Signifikanzniveau <span class="math inline">\(\alpha\)</span> bzw. ein zweiseitiges Konfidenzniveau <span class="math inline">\(1 - \frac{\alpha}{2}\)</span> fest.</li>
<li>Bestimmen Sie den Stichprobenmittelwert <span class="math inline">\(\bar{x}\)</span>.</li>
<li>Bestimmen Sie die Stichprobenstandardabweichung <span class="math inline">\(s\)</span>, die Stichprobengröße <span class="math inline">\(N\)</span> und den empirischen Standardfehler <span class="math inline">\(\frac{s_{n-1}}{\sqrt{N}}\)</span>.</li>
<li>Bestimmen Sie die Werte der Normal- bzw. der t-Verteilung für das gewählte Konfidenzniveau - für einen zweiseitigen Hypothesentest <span class="math inline">\(\frac{\alpha}{2}\)</span> und <span class="math inline">\(1 - \frac{\alpha}{2}\)</span></li>
<li>Berechnen Sie das Konfidenzintervall <span class="math inline">\(\bar{x} \pm t_{\alpha / 2} ~ \frac{s_{n-1}}{\sqrt{n}}\)</span>.</li>
</ol>
<p>Dieses Konfidenzintervall sagt für eine gewählte Wahrscheinlichkeit aus, in welchem Bereich der Mittelwert einer erneut durchgeführten Messreihe oder, wenn die unbekannte systematische Messabweichung Null (oder vernachlässigbar) ist, der <em>wahre Wert</em> liegen wird.<br>
Dagegen gibt die Standardabweichung <span class="math inline">\(s\)</span> Auskunft darüber, in welchem Bereich ein einzelner Messwert liegen wird. Die Sicherheit dieser Aussage kann durch Ausweitung des Konfidenzintervalls erhöht werden (bspw. <span class="math inline">\(2 \cdot s\)</span>).</p>
<p><span class="citation" data-cites="Hempel-2016">[@Hempel-2016, S. 3-7]</span></p>
<p>Im folgenden Beispiel wird das Vorgehen gezeigt. Dabei wird auch die Pandas-Methode <code>.sem()</code> zur einfachen Berechnung des Standardfehlers vorgestellt.</p>
<div id="nte-fehlerstatistik" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.5: Fehlerstatistik
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Aus dem im vorherigen Kapitel behandelten Experiment wird die Messreihe für das Gewicht 503g ausgewählt.</p>
<div id="de255a66" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dateipfad <span class="op">=</span> <span class="st">"01-daten/hooke_data.csv"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>hooke <span class="op">=</span> pd.read_csv(filepath_or_buffer <span class="op">=</span> dateipfad, sep <span class="op">=</span> <span class="st">';'</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>hooke.drop(index <span class="op">=</span> <span class="dv">113</span>, inplace <span class="op">=</span> <span class="va">True</span>) <span class="co"># Fehlwert, siehe vorheriges Kapitel</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>hooke_503g <span class="op">=</span> hooke.loc[hooke[<span class="st">'mass'</span>] <span class="op">==</span> <span class="dv">503</span>, :]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hooke_503g.head(), hooke_503g.describe(), sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    no  mass  distance
40  40   503    158.43
41  41   503    158.43
42  42   503    158.60
43  43   503    158.76
44  44   503    159.05

             no   mass    distance
count  10.00000   10.0   10.000000
mean   44.50000  503.0  159.314000
std     3.02765    0.0    0.781099
min    40.00000  503.0  158.430000
25%    42.25000  503.0  158.640000
50%    44.50000  503.0  159.220000
75%    46.75000  503.0  159.965000
max    49.00000  503.0  160.610000</code></pre>
</div>
</div>
<p>Betrachten wir für diese Messreihe noch einmal das arithmetische Mittel (das unbereinigte Messergebnis) und den Standardfehler des Mittelwerts (das statistische Streuungsmaß des Mittelwerts). Die Methode <code>.sem()</code> berechnet den empirischen Standardfehler des Mittelwerts (standardmäßig ist der Parameter <code>ddof = 1</code> gesetzt.)</p>
<p>Ausgabe auf 3 Dezimalstellen genau.</p>
<div id="f3d16f57" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Gewicht in Gramm: </span><span class="sc">{</span>hooke_503g[<span class="st">'mass'</span>]<span class="sc">.</span>unique()<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Mittelwert der Messwerte: </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss"> cm"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"empirischer Standardfehler: </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>sem()<span class="sc">:.3f}</span><span class="ss"> cm"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>      sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Gewicht in Gramm: [503]
Mittelwert der Messwerte: 159.314 cm
empirischer Standardfehler: 0.247 cm</code></pre>
</div>
</div>
<p>Die Messunsicherheit wird auf 2 Dezimalstellen genau aufgerundet. Dafür kann die NumPy-Funktion <code>np.ceil()</code> verwendet werden. Diese rundet allerdings zur nächsten Ganzzahl, ein Parameter, um auf eine bestimmte Dezimalstelle zu runden, ist nicht verfügbar. Deshalb muss die Dezimalstelle um die gewünschte Anzahl Stellen durch Multiplikation mit der entsprechenden Zehnerpotenz verschoben werden. Für 2 Dezimalstellen entsprechend um <span class="math inline">\(10^2\)</span>: <code>np.ceil(wert * 100) / 100</code>.</p>
<div id="7d9af844" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>wert <span class="op">=</span> pd.Series([<span class="fl">0.247</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.ceil(wert <span class="op">*</span> <span class="dv">100</span>) <span class="op">/</span> <span class="dv">100</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># mit Pandas-Methoden</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(wert.mul(<span class="dv">100</span>).<span class="bu">apply</span>(np.ceil).div(<span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0    0.25
dtype: float64
0    0.25
dtype: float64</code></pre>
</div>
</div>
<p>Für die Verkettung mit weiteren Methoden in Pandas muss die Rückgabe der Funktion, ein NumPy-Skalar oder -Array, wieder in eine <code>pd.Series</code> umgewandelt werden.</p>
<div id="a460a70e" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Gewicht in Gramm: </span><span class="sc">{</span>hooke_503g[<span class="st">'mass'</span>]<span class="sc">.</span>unique()<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Mittelwert der Messwerte: </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss"> cm"</span>,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"empirischer Standardfehler: </span><span class="sc">{</span> ( sem_hooke_503g<span class="op">:=</span> pd.Series(hooke_503g[<span class="st">'distance'</span>].sem()).mul(<span class="dv">100</span>).<span class="bu">apply</span>(np.ceil).div(<span class="dv">100</span>) )<span class="sc">.</span>item() <span class="sc">:.3f}</span><span class="ss"> cm"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"vollständiges Messergebnis: </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>mean()<span class="sc">.</span><span class="bu">round</span>(<span class="dv">2</span>)<span class="sc">:.2f}</span><span class="ss"> cm ± </span><span class="sc">{</span>sem_hooke_503g<span class="sc">.</span>item()<span class="sc">}</span><span class="ss"> cm"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>      sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Gewicht in Gramm: [503]
Mittelwert der Messwerte: 159.314 cm
empirischer Standardfehler: 0.250 cm
vollständiges Messergebnis: 159.31 cm ± 0.25 cm</code></pre>
</div>
</div>
<p>Zusätzliche Angabe des 95-%-Konfidenzintervalls.</p>
<div id="d06b0ad3" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-Wert bestimmen für Signifikanzniveau (alpha-Niveau) 1 - 95 % wählen</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> hooke_503g.shape[<span class="dv">0</span>] <span class="co"># Anzahl Zeilen</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>t_wert <span class="op">=</span> scipy.stats.t.ppf(q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> alpha<span class="op">/</span><span class="dv">2</span>, df <span class="op">=</span> n <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95-%-Konfidenzintervall : </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>mean()<span class="sc">.</span><span class="bu">round</span>(<span class="dv">2</span>)<span class="sc">}</span><span class="ss"> cm  ± </span><span class="sc">{</span>t_wert<span class="sc">:.4f}</span><span class="ss"> * </span><span class="sc">{</span>sem_hooke_503g<span class="sc">.</span>item()<span class="sc">}</span><span class="ss"> cm"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="ss">f"95-%-Konfidenzintervall : </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>mean()<span class="sc">.</span><span class="bu">round</span>(<span class="dv">2</span>)<span class="sc">}</span><span class="ss"> cm  ± </span><span class="sc">{</span>( t_wert <span class="op">*</span> sem_hooke_503g.item() )<span class="sc">.</span><span class="bu">round</span>(<span class="dv">2</span>)<span class="sc">:.2f}</span><span class="ss"> cm"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="ss">f"untere 95-%-Intervallgrenze: </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>mean()<span class="sc">.</span><span class="bu">round</span>(<span class="dv">2</span>) <span class="op">-</span> <span class="bu">round</span>(t_wert <span class="op">*</span> sem_hooke_503g.item(), <span class="dv">2</span>)<span class="sc">:.2f}</span><span class="ss"> cm"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="ss">f"obere 95-%-Intervallgrenze: </span><span class="sc">{</span>hooke_503g[<span class="st">'distance'</span>]<span class="sc">.</span>mean()<span class="sc">.</span><span class="bu">round</span>(<span class="dv">2</span>) <span class="op">+</span> <span class="bu">round</span>(t_wert <span class="op">*</span> sem_hooke_503g.item(), <span class="dv">2</span>)<span class="sc">:.2f}</span><span class="ss"> cm"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>95-%-Konfidenzintervall : 159.31 cm  ± 2.2622 * 0.25 cm
95-%-Konfidenzintervall : 159.31 cm  ± 0.57 cm
untere 95-%-Intervallgrenze: 158.74 cm
obere 95-%-Intervallgrenze: 159.88 cm</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="fehlerfortpflanzung" class="level3" data-number="52.7.3">
<h3 data-number="52.7.3" class="anchored" data-anchor-id="fehlerfortpflanzung"><span class="header-section-number">52.7.3</span> 3. Fehlerfortpflanzung</h3>
<p>Die Fehlerfortpflanzung wird verwendet, wenn</p>
<ul>
<li><strong>mehrere Eingangsgrößen</strong>,</li>
<li><strong>die durch eine Funktion die Ergebnisgröße ergeben</strong>,</li>
</ul>
<p>gemessen werden.</p>
<p>Um die Messunsicherheit einer Größe <span class="math inline">\(Y\)</span>, die durch eine Funktion <span class="math inline">\(y = f(x_1, x_2, ..., x_m)\)</span> geschätzt wird, zu ermitteln, gibt es zwei Verfahren:</p>
<ul>
<li>die <strong>lineare Fehlerfortpflanzung</strong> wird benutzt, wenn die Unsicherheit der beteiligten Größen durch Fehlerabschätzung einer <strong>Einzelmessung</strong> ermittelt wurden.</li>
<li>die <strong>Gauß’sche Fehlerfortpflanzung</strong> wird benutzt, wenn die Unsicherheit aus einer <strong>Mehrfachmessung statistisch ermittelt</strong> und mit Konfidenzintervallen angegeben werden.</li>
</ul>
<p><span class="citation" data-cites="Hempel-2016">[@Hempel-2016, S. 8-9]</span></p>
<section id="lineare-fehlerfortpflanzung" class="level4" data-number="52.7.3.1">
<h4 data-number="52.7.3.1" class="anchored" data-anchor-id="lineare-fehlerfortpflanzung"><span class="header-section-number">52.7.3.1</span> Lineare Fehlerfortpflanzung</h4>
<p>Die lineare Fehlerfortpflanzung betrachtet, wie sich die <strong>Größtfehler</strong> mehrerer gemessener Größen im ungünstigsten Fall auswirken. Es wird also der <strong>Größtfehler</strong> der gesuchten Größe <span class="math inline">\(Y\)</span> berechnet. (vgl. <span class="citation" data-cites="DIN1319-3">@DIN1319-3</span>, S. 9)</p>
<p>Für eine Funktion mit zwei Eingangsgrößen <span class="math inline">\(f = f(x_1, x_2)\)</span> wird der Größtfehler <span class="math inline">\(\Delta f\)</span> aus den Größtfehlern <span class="math inline">\(\Delta x_1\)</span> und <span class="math inline">\(\Delta x_2\)</span> ermittelt.</p>
<p><span class="math display">\[
f + \Delta f = f(x_1 + \Delta x_1, x_2 + \Delta x_2)
\]</span></p>
<p>Unter der Voraussetzung gegenüber den Messwerten kleiner Fehler kann der Fehler <span class="math inline">\(\Delta f\)</span> durch die Beträge der partiellen Ableitung des ersten Glieds der Taylorreihe berechnet werden (siehe Beispiel).</p>
<p><span class="math display">\[
f + \Delta f = f(x_1, x_2) + | \frac{\partial f(x_1, x_2)}{\partial x_1}  | \cdot \Delta x_1 + | \frac{\partial f(x_1, x_2)}{\partial x_2} | \cdot \Delta x_2
\]</span></p>
<p>Wann sind die Fehler gegenüber den Messwerten klein? Dafür gibt es leider keine absolute Grenze. Es kommt hierbei darauf an, dass bei der Taylor-Entwicklung die Polynome höheren Grades deutlich kleiner als der lineare Term sind und somit vernachlässigt werden können, wenn das <span class="math inline">\(x\)</span> klein ist. Die Entscheidung hängt letztlich von der benötigten Genauigkeit ab.</p>
<div id="nte-taylorreihe" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.6: Taylorreihe
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/F2lKRaUguBM" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
<p>Die Taylorreihe - einfach erklärt von Denkbar ist abrufbar auf <a href="https://www.youtube.com/watch?v=F2lKRaUguBM">YouTube</a>. 2015</p>
</div>
</div>
</div>
<div id="nte-partielleableitung" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.7: Partielle Ableitung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Die partielle Ableitung ist die Ableitung einer Funktion mit mehreren Variablen nach einer Variablen, wobei die übrigen Variablen als Konstanten behandelt werden.</p>
<p>Für eine Funktion <span class="math inline">\(f(x, y) = 2x + y^2\)</span> wird die partielle Ableitung nach x so ausgedrückt:</p>
<p><span class="math inline">\(\frac{\partial f(x, y)}{\partial x}\)</span></p>
<ul>
<li>Das Symbol ∂ ist die kursive Darstellung des kyrillischen Kleinbuchstaben д (d) und wird als “del” gelesen. Es zeigt an, das eine partielle Ableitung durchgeführt wird.</li>
<li>Im Zähler steht die Funktion, die abgeleitet werden soll. Im Nenner steht die Variable nach der abgeleitet wird. Der Term wird gelesen als “del f von x und y nach del x”.</li>
</ul>
<p>Die partielle Ableitung <span class="math inline">\(\frac{\partial f(x, y)}{\partial x} = 2\)</span>. <span class="math inline">\(y^2\)</span> wird als Konstante behandelt (z. B. <span class="math inline">\(5^2\)</span> ) und ist abgeleitet Null.</p>
<p>Die partielle Ableitung <span class="math inline">\(\frac{\partial f(x, y)}{\partial y} = 2y\)</span>. <span class="math inline">\(2x\)</span> wird als Konstante behandelt (z. B. <span class="math inline">\(2 \cdot 3\)</span> ) und ist abgeleitet Null.</p>
</div>
</div>
</div>
<p>Der Größtfehler ergibt sich aus: <span class="math display">\[
\Delta f = | \frac{\partial f(x_1, x_2)}{\partial x_1}  | \cdot \Delta x_1 + | \frac{\partial f(x_1, x_2)}{\partial x_2} | \cdot \Delta x_2
\]</span></p>
<p><span class="citation" data-cites="Hempel-2016">[@Hempel-2016, S. 9-10]</span></p>
<p>Bzw. in Kurzschreibweise für <span class="math inline">\(i = N\)</span> Eingangsgrößen: <span class="math display">\[
\Delta f(x_i) = \pm \sum_{i=1}^{N} | \frac{\partial f}{\partial x_i} \cdot \Delta x_i |
\]</span></p>
<p><span class="citation" data-cites="EdenGebhard-2024">[nach @EdenGebhard-2024, S. 35, Notation angepasst]</span></p>
<div id="nte-beispiellineareff" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.8: Beispiel Federkonstante
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Beispielhaft betrachten wir die erste Messung aus der Messreihe mit dem Gewicht 503 Gramm.</p>
<div id="5cd6db55" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>hooke_503g_einzelwert <span class="op">=</span> hooke_503g.iloc[<span class="dv">0</span>, :].copy()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hooke_503g_einzelwert)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>no           40.00
mass        503.00
distance    158.43
Name: 40, dtype: float64</code></pre>
</div>
</div>
<p>Da mehrere Größen betrachtet werden, werden die Messwerte in eine SI-Einheit umgerechnet. Als Nullpunkt wird die erste Messung der Messreihe mit dem Gewicht 0 Gramm aufgefasst.</p>
<div id="403ea8ee" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>hooke_503g_einzelwert[<span class="st">'mass'</span>] <span class="op">=</span> hooke_503g_einzelwert[<span class="st">'mass'</span>] <span class="op">/</span> <span class="dv">1000</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>hooke_503g_einzelwert[<span class="st">'distance'</span>] <span class="op">=</span> hooke_503g_einzelwert[<span class="st">'distance'</span>] <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>nullpunkt <span class="op">=</span> hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> <span class="dv">0</span>].loc[: , <span class="st">'distance'</span>].head(n <span class="op">=</span> <span class="dv">1</span>) <span class="op">/</span><span class="dv">100</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Nullpunkt in Metern: </span><span class="sc">{</span>nullpunkt<span class="sc">.</span>item()<span class="sc">:.3f}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>hooke_503g_einzelwert[<span class="st">'ausdehnung'</span>] <span class="op">=</span> (hooke_503g_einzelwert[<span class="st">'distance'</span>].item() <span class="op">-</span>nullpunkt.item()) <span class="op">*</span> <span class="op">-</span><span class="dv">1</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(hooke_503g_einzelwert)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nullpunkt in Metern: 1.733

no            40.0000
mass           0.5030
distance       1.5843
ausdehnung     0.1489
Name: 40, dtype: float64</code></pre>
</div>
</div>
<p>Für die Federkonstante gilt (die Abstandsänderung <span class="math inline">\(\Delta x\)</span> wird mit <span class="math inline">\(s\)</span> notiert):</p>
<p><span class="math display">\[
k = \frac{m \cdot g}{\Delta{x}} = \frac{m \cdot g}{s}
\]</span></p>
<p>Einsetzen der Werte (<span class="math inline">\(s\)</span> steht nun für Sekunde, <span class="math inline">\(m\)</span> für Meter): <span class="math display">\[
k = \frac{0,503 ~ kg \cdot 9,81 m}{0,1489 ~ m \cdot s^2} = \frac{0,503 \cdot 9,81}{0,1489} \frac{N}{{m}} = 33.139 \frac{N}{{m}}
\]</span></p>
<p>So gilt für den Größtfehler der Funktion: <span class="math display">\[
\Delta k(m, s) = | \frac{\partial f(m, s)}{\partial m} | \cdot \Delta m + | \frac{\partial f(m, s)}{\partial s} | \cdot \Delta s
\]</span></p>
<p>Im ersten Schritt werden die partiellen Ableitungen der Funktion <span class="math inline">\(k = \frac{m \cdot g}{s}\)</span> gebildet. Die partielle Ableitung nach <span class="math inline">\(m\)</span> lautet mit Faktorregel: <span class="math display">\[
\frac{\partial f(m, s)}{\partial m} = \frac{\partial}{\partial m} \frac{m \cdot g}{s} = \frac{\partial}{\partial m} m \cdot \frac{g}{s} = 1 \cdot \frac{g}{s} = \frac{g}{s}
\]</span></p>
<p>Die partielle Ableitung nach s lautet: <span class="math display">\[
\frac{\partial f(m, s)}{\partial s} = \frac{\partial}{\partial s} \frac{m \cdot g}{s} = - \frac {m \cdot g}{s^{2}}
\]</span></p>
<p>Der Größtfehler ergibt sich also durch: <span class="math display">\[
\Delta k = | \frac{g}{s} | \cdot \Delta m ~ + ~ | (-) \frac {m \cdot g}{s^{2}} | \cdot \Delta s
\]</span></p>
<p>Im zweiten Schritt wird der Größtfehler der beteiligten Größen ermittelt.</p>
<ul>
<li>Die Masse <span class="math inline">\(m\)</span> der verwendeten Gewichte wurde mit einer Küchenwaage ermittelt, deren Ableseabweichung auf <span class="math inline">\(e_r (m) = 0,5 g = 0,0005 ~ kg\)</span> geschätzt wird. Eine systematische Messabweichung ist nicht bekannt.<br>
Der Größtfehler der Masse beträgt also <span class="math inline">\(\Delta m = 0,0005 ~ kg\)</span>.</li>
<li>Der Größtfehler der Abstandsmessung beträgt <span class="math inline">\(e_{r}(s) = 0,01 cm + 0,3 cm = 0,0031 m\)</span>.</li>
</ul>
<p>Die Messwerte, die Konstante <span class="math inline">\(g\)</span> und die Größtfehler werden eingesetzt. <span class="math display">\[
\Delta k = | \frac{9,81 m}{{s}^2 \cdot 0,1489 m} | \cdot 0,0005 ~ kg ~ + ~ | (-) \frac{0,503 ~ kg \cdot 9,81  m}{{s}^2 \cdot (0,1489 m)^2} | \cdot 0,0031 m
\]</span></p>
<p>Trennen von Werten und Einheiten: <span class="math display">\[
\Delta k = | \frac{9,81 \cdot 0,0005}{ 0,1489 } \frac{m \cdot }{{s}^2 \cdot m} | ~ + | (-) \frac{0,503 \cdot 9,81 \cdot 0,0031}{0,02217121} \frac{kg \cdot m^2}{{s}^2 \cdot m^2} |
\]</span></p>
<p>Berechnen und Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen: <span class="math display">\[
\Delta k = | 0,0329 \frac{N}{{m}} | ~ + | (-) 0,6899 \frac{N \cdot m}{{m^2}} |
\]</span></p>
<p>Meter im zweiten Term kürzen: <span class="math display">\[
\Delta k = |0,0329 \frac{N}{{m}} | ~ + | (-) 0,6899 \frac{N}{{m}} |
\]</span></p>
<p>Die Messunsicherheit wird auf zwei Dezimalstellen aufgerundet. <span class="math display">\[
\Delta k = 0,7228 \frac{N}{{m}} \approx 0,73 \frac{N}{{m}}
\]</span></p>
<p>Das vollständige Messergebnis lautet somit: <span class="math display">\[
k = 33,14 \frac{N}{m}; \Delta k = 0,73 \frac{N}{{m}}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="gaußsche-fehlerfortpflanzung" class="level4" data-number="52.7.3.2">
<h4 data-number="52.7.3.2" class="anchored" data-anchor-id="gaußsche-fehlerfortpflanzung"><span class="header-section-number">52.7.3.2</span> Gauß’sche Fehlerfortpflanzung</h4>
<p>Bei der Gauß’schen Fehlerfortpflanzung wird unterstellt, dass sich die Messunsicherheiten der beteiligten Größen teilweise kompensieren können. Dadurch wird eine realistischere Abschätzung der Messunsicherheit erreicht.</p>
<p>Die Ermittlung der Messunsicherheit ist in DIN 1319-3 geregelt. Für eine Funktion <span class="math inline">\(Y = f(x_1, x_2, ..., x_m)\)</span> ermittelt sich die Messunsicherheit aus der Messunsicherheit der beteiligten Größen. Dazu werden die Varianzen der Mittelwerte verwendet (<span class="citation" data-cites="DIN1319-3">@DIN1319-3</span>, Gleichung (29), S. 11). <span class="math display">\[
u^2(x_i) = s^2(\bar{x_i}) = s_i^2/n_i ~ ; ~ s_i^2 = \frac{1}{n_i - 1} \sum_{j = 1}^{n_i} (x_{ij - \bar{x_i}})^2
\]</span></p>
<p><em>Hinweis: In der Regel wird man die empirische Standardabweichung <span class="math inline">\(s_{n-1}\)</span> verwenden.</em><br>
<em>Hinweis: In der DIN wird der arithmetische Mittelwert einer Messreihe statt mit <span class="math inline">\(\bar{x}\)</span> mit <span class="math inline">\(\bar{v}\)</span> geschrieben</em>.</p>
<p>Die Messunsicherheit der beteiligten Größen wird also über den Standardfehler des Mittelwerts der beteiligten Größen ermittelt: <span class="math display">\[
u(x_i) = s_i/\sqrt{n_i}
\]</span></p>
<p><em>Hinweis: In der Regel wird man die empirische Standardabweichung <span class="math inline">\(s_{n-1}\)</span> verwenden.</em></p>
<p><span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 11]</span></p>
<p>Die Unsicherheit der Funktion <span class="math inline">\(y = f(x_1, x_2, ..., x_m)\)</span> berechnet sich wie folgt (DIN 1319-3, Gleichung (43)):</p>
<p><span class="math display">\[
u(y) = \sqrt{\sum_{i = 1}^{m} (\frac{\partial f}{\partial x_i})^2 \cdot u^2(x_i)}
\]</span></p>
<p>Die quadrierten Terme können auch zusammengefasst werden:</p>
<p><span class="math display">\[
u(y) = \sqrt{\sum_{i = 1}^{m} \left(\frac{\partial f}{\partial x_i} \cdot u(x_i)\right)^2}
\]</span></p>
<p>Für eine Funktion mit zwei Eingangsgrößen <span class="math inline">\(y = f(x_1, x_2)\)</span> berechnet sich die Unsicherheit der Ergebnisgröße beispielsweise wie folgt:</p>
<p><span class="math display">\[
u(y) = \sqrt{ (\frac{\partial f}{\partial x_1} \cdot \sigma_{x_1})^2 + (\frac{\partial f}{\partial x_2} \cdot \sigma_{x_2})^2 }
\]</span></p>
<p><em>Hinweis: In der Regel wird man die empirische Standardabweichung <span class="math inline">\(s_{n-1} / \sqrt{N}\)</span> verwenden.</em></p>
<div id="nte-beispiel503g" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.9: Beispiel Messreihe 503 Gramm
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Betrachten wir noch einmal die Messreihe für das Gewicht 503 Gramm. Es soll das vereinbarte Konfidenzniveau <span class="math inline">\(95 ~ \%\)</span> gelten.</p>
<div id="05b62d0b" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Messdaten aus dem Kapitel hooke.qmd wiederherstellen</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co">## Datei einlesen und Fehler entfernen</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>dateipfad <span class="op">=</span> <span class="st">"01-daten/hooke_data.csv"</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>hooke <span class="op">=</span> pd.read_csv(filepath_or_buffer <span class="op">=</span> dateipfad, sep <span class="op">=</span> <span class="st">';'</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>hooke.drop(index <span class="op">=</span> <span class="dv">113</span>, inplace <span class="op">=</span> <span class="va">True</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co">## Abstandsmessung auf Nullpunkt normieren</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>nullpunkt <span class="op">=</span> hooke[hooke[<span class="st">'mass'</span>] <span class="op">==</span> <span class="dv">0</span>].loc[: , <span class="st">'distance'</span>].mean()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>hooke[<span class="st">'ausdehnung'</span>] <span class="op">=</span> hooke[<span class="st">'distance'</span>].sub(nullpunkt).mul(<span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Messreihe 503 Gramm auswählen</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>hooke_503g <span class="op">=</span> hooke.loc[hooke[<span class="st">'mass'</span>] <span class="op">==</span> <span class="dv">503</span>, :].copy()</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co">## Masse in kg, Abstand und Ausdehnung in m umrechnen</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>hooke_503g[<span class="st">'mass'</span>] <span class="op">=</span> hooke_503g[<span class="st">'mass'</span>].div(<span class="dv">1000</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>hooke_503g[<span class="st">'distance'</span>] <span class="op">=</span> hooke_503g[<span class="st">'distance'</span>].div(<span class="dv">100</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>hooke_503g[<span class="st">'ausdehnung'</span>] <span class="op">=</span> hooke_503g[<span class="st">'ausdehnung'</span>].div(<span class="dv">100</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="co"># t-Wert bestimmen für Signifikanzniveau (alpha-Niveau) 1 - 95 % wählen</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>n_ausdehnung <span class="op">=</span> hooke_503g.shape[<span class="dv">0</span>] <span class="co"># Anzahl Zeilen</span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>t_wert_ausdehnung <span class="op">=</span> scipy.stats.t.ppf(q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> alpha<span class="op">/</span><span class="dv">2</span>, df <span class="op">=</span> n_ausdehnung <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Ausgabe</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Gewicht in Kilogramm: </span><span class="sc">{</span>hooke_503g[<span class="st">'mass'</span>]<span class="sc">.</span>unique()<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Mittlere Ausdehnung: </span><span class="sc">{</span>hooke_503g[<span class="st">'ausdehnung'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss"> m"</span>,</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"empirischer Standardfehler: </span><span class="sc">{</span> (sem_hooke_503g<span class="op">:=</span> pd.Series(hooke_503g[<span class="st">'ausdehnung'</span>].sem()))<span class="sc">.</span>item() <span class="sc">:.6f}</span><span class="ss"> m"</span>,</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"t-Wert der Ausdehnung: </span><span class="sc">{</span>t_wert_ausdehnung<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"95-%-Intervallgrenzen: </span><span class="sc">{</span>(hooke_503g[<span class="st">'ausdehnung'</span>].mean() <span class="op">-</span> t_wert_ausdehnung <span class="op">*</span> sem_hooke_503g)<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss"> m ≤ </span><span class="sc">{</span>hooke_503g[<span class="st">'ausdehnung'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss"> m ≤ </span><span class="sc">{</span>(hooke_503g[<span class="st">'ausdehnung'</span>].mean() <span class="op">+</span> t_wert_ausdehnung <span class="op">*</span> sem_hooke_503g)<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss"> m"</span>,</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>      sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Gewicht in Kilogramm: [0.503]
Mittlere Ausdehnung: 0.1432 m
empirischer Standardfehler: 0.002470 m
t-Wert der Ausdehnung: 2.2622
95-%-Intervallgrenzen: 0.1376 m ≤ 0.1432 m ≤ 0.1488 m</code></pre>
</div>
</div>
<p>Für die Federkonstante gilt (die Abstandsänderung <span class="math inline">\(\Delta x\)</span> wird mit <span class="math inline">\(s\)</span> notiert):<br>
<span class="math display">\[
k = \frac{m \cdot g}{\Delta{x}} = \frac{m \cdot g}{s}
\]</span></p>
<p><span class="math display">\[
k = \frac{0,503 ~ kg \cdot 9,81 m}{0,1432 ~ m \cdot s^2} = \frac{0,503 \cdot 9,81}{0,1432} \frac{N}{{m}} = 34,458\frac{N}{{m}}
\]</span></p>
<p>&nbsp;</p>
<p>Um die Unsicherheit der Ergebnisgröße <span class="math inline">\(k\)</span> nach der Gauß`schen Fehlerfortpflanzung zu bestimmen, müsste die Masse des verwendeten Gewichts ebenfalls durch eine Messreihe bestimmt worden sein. (Wie Messreihen und Einzelmessungen kombiniert werden können, wird im nächsten Abschnitt gezeigt.) Deshalb wird angenommen, dass mehrere Messungen zur Ermittlung des Gewichts durchgeführt wurden. Die Messreihe sowie ihr Mittelwert und Standardfehler könnten wie folgt aussehen:</p>
<div id="d8ed307b" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>messreihe_503g <span class="op">=</span> pd.Series([<span class="dv">503</span> , <span class="dv">503</span>, <span class="dv">504</span>, <span class="dv">502</span>, <span class="dv">503</span>, <span class="dv">502</span>, <span class="dv">503</span>, <span class="dv">504</span>])</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>messreihe_503g <span class="op">/=</span> <span class="dv">1000</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># t-Wert bestimmen für Signifikanzniveau (alpha-Niveau) 1 - 95 % wählen</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>alpha <span class="op">=</span> <span class="fl">0.05</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>n_masse <span class="op">=</span> messreihe_503g.shape[<span class="dv">0</span>] <span class="co"># Anzahl Elemente</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>t_wert_masse <span class="op">=</span> scipy.stats.t.ppf(q <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> alpha<span class="op">/</span><span class="dv">2</span>, df <span class="op">=</span> n_masse <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Ausgabe</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"arithmetisches Mittel der Masse: </span><span class="sc">{</span>messreihe_503g<span class="sc">.</span>mean()<span class="sc">}</span><span class="ss"> kg"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"empirischer Standardfehler: </span><span class="sc">{</span> (sem_messreihe_503g<span class="op">:=</span> pd.Series(messreihe_503g.sem()))<span class="sc">.</span>item() <span class="sc">:.6f}</span><span class="ss"> kg"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"t-Wert der Masse: </span><span class="sc">{</span>t_wert_masse<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"95-%-Intervallgrenzen: </span><span class="sc">{</span>(messreihe_503g.mean() <span class="op">-</span> t_wert_masse <span class="op">*</span> sem_messreihe_503g)<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss"> kg - </span><span class="sc">{</span>(messreihe_503g.mean() <span class="op">+</span> t_wert_masse <span class="op">*</span> sem_messreihe_503g)<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss"> kg"</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>      sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>arithmetisches Mittel der Masse: 0.503 kg
empirischer Standardfehler: 0.000267 kg
t-Wert der Masse: 2.3646
95-%-Intervallgrenzen: 0.5024 kg - 0.5036 kg</code></pre>
</div>
</div>
<p>Die Gauß’sche Fehlerfortpflanzung wird ähnlich zur linearen Fehlerfortpflanzung berechnet.</p>
<p><span class="math display">\[
u(k(m, s)) = \sqrt{ (\frac{\partial f(m, s)}{\partial m} \cdot \sigma_{m})^2 + (\frac{\partial f(m, s)}{\partial s} \cdot \sigma_{s})^2 }
\]</span></p>
<p>Die partiellen Ableitungen werden eingesetzt. <span class="math display">\[
u(k(m, s)) = \sqrt{ ( \frac{g}{s} \cdot \sigma_{m})^2 + (- \frac {m \cdot g}{s^{2}} \cdot \sigma_{s})^2 }
\]</span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Vollständiges Messergebnis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">95-%-Vertrauensintervall</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Die Messwerte, die Konstante <span class="math inline">\(g\)</span> und die Standardfehler der Mittelwerte werden eingesetzt. <span class="math display">\[
u(k(m, s)) = \sqrt{ ( \frac{9,81 m}{{s}^2 \cdot  0,1432 m}  \cdot 0,000267 ~ kg)^2 + ((-) \frac{0,503 ~ kg \cdot 9,81  m}{{s}^2 \cdot ( 0,1432 m)^2} \cdot  0,00247 m)^2 }
\]</span></p>
<p>Trennen von Werten und Einheiten: <span class="math display">\[
u(k(m, s)) = \sqrt{ ( \frac{9,81 \cdot 0,000267}{  0,1432 } \frac{m \cdot kg}{{s}^2 \cdot m})^2 + ((-) \frac{0,503 \cdot 9,81 \cdot 0,00247}{0,02051} \frac{kg \cdot m^2}{{s}^2 \cdot m^2})^2 }
\]</span></p>
<p>Berechnen, Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen und Meter im 2. Term kürzen: <span class="math display">\[
u(k(m, s)) = \sqrt{ ( \frac{9,81 \cdot 0,000267}{  0,1432 } \frac{N}{m})^2 + ((-) \frac{0,503 \cdot 9,81 \cdot 0,00247}{0,02051} \frac{N}{m})^2 }
\]</span></p>
<p>Zusammenfassen: <span class="math display">\[
u(k(m, s)) = \sqrt{ ( 0,0183 \frac{N}{m})^2 + ((-) 0,594 \frac{N}{m})^2 }
\]</span></p>
<p>Ausrechnen: <span class="math display">\[
u(k(m, s)) = 0,595 \frac{N}{m} \approx 0,60 \frac{N}{m}
\]</span></p>
<p>Das vollständige Messergebnis lautet somit: <span class="math display">\[
k = 34,46 \frac{N}{m} \pm 0,60 \frac{N}{m}
\]</span></p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Zusätzlich zum vollständigen Messergebnis kann ein Vertrauensintervall angegeben werden. Entsprechend der vereinbarten Vertrauenswahrscheinlichkeit, sind die entsprechenden t-Werte als Korrekturfaktoren einzusetzen.</p>
<p><span class="math display">\[
u(k(m, s)) = \sqrt{ ( \frac{g}{s} \cdot t_{\alpha/2} \cdot \sigma_{m})^2 + (- \frac {m \cdot g}{s^{2}} \cdot t_{\alpha/2} \cdot \sigma_{s})^2 }
\]</span></p>
<p>Dies sind für die Masse <span class="math inline">\(t = 2,3646\)</span> und für die Ausdehnung <span class="math inline">\(t = 2,2622\)</span>.</p>
<p>Die Messwerte, die Konstante <span class="math inline">\(g\)</span>, der Standardfehler des Mittelwerts und der t-Wert werden in den ersten Term eingesetzt. <span class="math display">\[
(\frac{g}{s} \cdot t_{\alpha/2} \cdot \sigma_{m})^2 = ( \frac{9,81 m}{{s}^2 \cdot 0,1432 m}  \cdot 2,3646 \cdot 0,000267 ~ kg)^2
\]</span></p>
<p>Trennen von Werten und Einheiten, Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen: <span class="math display">\[
(\frac{9,81 \cdot 2,3646 \cdot 0,000267}{  0,1432 } \frac{m \cdot kg}{{s}^2 \cdot m})^2 = (0,0433 \frac{N}{m})^2
\]</span></p>
<p>Die Messwerte, die Konstante <span class="math inline">\(g\)</span>, der Standardfehler des Mittelwerts und der t-Wert werden in den zweiten Term eingesetzt. <span class="math display">\[
(- \frac {m \cdot g}{s^{2}} \cdot t_{\alpha/2} \cdot \sigma_{s})^2 =  ((-) \frac{0,503 ~ kg \cdot 9,81  m}{{s}^2 \cdot ( 0,1432 m)^2} \cdot  2,2622 \cdot  0,00247 m)^2
\]</span></p>
<p>Trennen von Werten und Einheiten, Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen und <span class="math inline">\(m\)</span> kürzen: <span class="math display">\[
((-) \frac{0,503 \cdot 9,81 \cdot  2,2622 \cdot 0,00247}{0,02051} \frac{kg \cdot m^2}{{s}^2 \cdot m^2})^2 = ((-) 1,344 \frac{N}{m})^2
\]</span></p>
<p>Die Formel lautet somit: <span class="math display">\[
u(k(m, s)) = \sqrt{ ( 0,0433 \frac{N}{m})^2 + ((-) 1,344 \frac{N}{m})^2 }
\]</span></p>
<p>Ausrechnen: <span class="math display">\[
u(k(m, s)) = 1,345 \frac{N}{m} \approx 1,35 \frac{N}{m}
\]</span></p>
<p>Die Intervallgrenzen lauten somit: <span class="math display">\[
k = 34,46 \frac{N}{m} \pm 1,35 \frac{N}{m}
\]</span></p>
<p>Also: <span class="math display">\[
k_{95\%} = 33,11 \frac{N}{m} \le 34,46 \frac{N}{m} \le 35,81 \frac{N}{m}
\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="übersicht-fehlerfortpflanzung-für-grundrechenarten-und-potenzprodukte" class="level4" data-number="52.7.3.3">
<h4 data-number="52.7.3.3" class="anchored" data-anchor-id="übersicht-fehlerfortpflanzung-für-grundrechenarten-und-potenzprodukte"><span class="header-section-number">52.7.3.3</span> Übersicht Fehlerfortpflanzung für Grundrechenarten und Potenzprodukte</h4>
<p>Einige Funktionen sind besonders leicht zu berechnen. In der folgenden Tabelle sind Rechenwege zur Ermittlung der Messunsicherheit nach der Gauß’schen Fehlerfortpflanzung (Standardfehler) und nach der linearen Fehlerfortpflanzung (Größtfehler) aufgelistet.</p>
<div class="border">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="00-bilder/tabelle-edengebhard2024.png" class="img-fluid figure-img" alt="Tabellarische Übersicht für die Berechnung des Größtfehlers in verschiedenen Fällen."></p>
<figcaption>Fehlerfortpflanzung für Grundrechenarten und Potenzprodukte</figcaption>
</figure>
</div>
<p><span class="citation" data-cites="EdenGebhard-2024">[@EdenGebhard-2024, S. 36]</span></p>
</div>
</section>
<section id="spezialfall-fehlerfortpflanzung-mit-einzelwerten" class="level4" data-number="52.7.3.4">
<h4 data-number="52.7.3.4" class="anchored" data-anchor-id="spezialfall-fehlerfortpflanzung-mit-einzelwerten"><span class="header-section-number">52.7.3.4</span> Spezialfall: Fehlerfortpflanzung mit Einzelwerten</h4>
<p>Ein Sonderfall ist die Ermittlung der Messunsicherheit, wenn diese sich aus statistischen Vertrauensbereichen und abgeschätzten Fehleranteilen aus einer Einzelmessung zusammensetzt.</p>
<p>Für die Berechnung eines Gesamtfehlers muss ein Kompromiss eingegangen werden.</p>
<ol type="1">
<li>Die lineare Fehlerfortpflanzung wird mit dem abgeschätzten Fehler und dem statistischen Vertrauensbereich durchgeführt.</li>
<li>Die Gauß’sche Fehlerfortpflanzung wird mit dem statistischen Vertrauensbereich durchgeführt und ein Fehleranteil addiert, der aus der linearen Fehlerfortpflanzung der abgeschätzten Fehler ermittelt wird.</li>
</ol>
<p>“Beide Verfahren sind wohl gleich gut (oder schlecht) als Kompromiss in der Laborpraxis geeignet.” (<span class="citation" data-cites="Hempel-2016">@Hempel-2016</span>, S. 9)</p>
<p>(<span class="citation" data-cites="Hempel-2016">@Hempel-2016</span>, S. 8 - 9)</p>
<p>Die DIN 1319 behandelt nur die Gauß’sche Fehlerfortpflanzung. Liegt für eine Eingangsgröße nur ein einzelner Wert vor, wird dieser als Schätzwert für diese Größe verwendet. Die Unsicherheit ist aus den verfügbaren Informationen oder nach der Erfahrung, zum Beispiel aus früheren Messungen, anzusetzen. <span class="citation" data-cites="DIN1319-3">[@DIN1319-3, S. 11]</span></p>
<p>Als Beispiel verwenden wir wieder die Messreihe für das Gewicht 503 Gramm.</p>
<div id="nte-beispieleinzelwert" class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note&nbsp;52.10: Beispiel Federkonstante
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="9ba3c44e" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ausgabe</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Gewicht in Kilogramm: </span><span class="sc">{</span>hooke_503g[<span class="st">'mass'</span>]<span class="sc">.</span>unique()<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"Mittlere Ausdehnung: </span><span class="sc">{</span>hooke_503g[<span class="st">'ausdehnung'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss"> m"</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"empirischer Standardfehler: </span><span class="sc">{</span> (sem_hooke_503g<span class="op">:=</span> pd.Series(hooke_503g[<span class="st">'ausdehnung'</span>].sem()))<span class="sc">.</span>item() <span class="sc">:.6f}</span><span class="ss"> m"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"t-Wert der Ausdehnung: </span><span class="sc">{</span>t_wert_ausdehnung<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"95-%-Intervallgrenzen: </span><span class="sc">{</span>(hooke_503g[<span class="st">'ausdehnung'</span>].mean() <span class="op">-</span> t_wert_ausdehnung <span class="op">*</span> sem_hooke_503g)<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss"> m ≤ </span><span class="sc">{</span>hooke_503g[<span class="st">'ausdehnung'</span>]<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss"> m ≤ </span><span class="sc">{</span>(hooke_503g[<span class="st">'ausdehnung'</span>].mean() <span class="op">+</span> t_wert_ausdehnung <span class="op">*</span> sem_hooke_503g)<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss"> m"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>      sep <span class="op">=</span> <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Gewicht in Kilogramm: [0.503]
Mittlere Ausdehnung: 0.1432 m
empirischer Standardfehler: 0.002470 m
t-Wert der Ausdehnung: 2.2622
95-%-Intervallgrenzen: 0.1376 m ≤ 0.1432 m ≤ 0.1488 m</code></pre>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Lineare Fehlerfortpflanzung</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Gauß’sche Fehlerfortpflanzung</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>Analog zur Fehlerabschätzung ergibt sich der Größtfehler der Federkonstante durch: <span class="math display">\[
\Delta k = | \frac{g}{s} | \cdot \Delta m ~ + ~ | (-) \frac {m \cdot g}{s^{2}} | \cdot \Delta s
\]</span></p>
<ul>
<li>Die Ableseabweichung der Küchenwaage wird auf <span class="math inline">\(e_r (m) = 0,5 g = 0,0005 ~ kg\)</span> geschätzt. Eine systematische Messabweichung ist nicht bekannt. Der Größtfehler der Masse beträgt also <span class="math inline">\(\Delta m = 0,0005 ~ kg\)</span></li>
<li>Der empirische Standardfehler der Ausdehnung beträgt <span class="math inline">\(\sigma_x = 0.00247 m\)</span> bzw. zum vereinbarten Vertrauensniveau von <span class="math inline">\(\sigma_{x 95 \%} = 0.00247 ~ m * 2.2622 = 0,00559 m\)</span></li>
</ul>
<p>Die Messwerte, die Konstante <span class="math inline">\(g\)</span> und die Größtfehler werden eingesetzt. <span class="math display">\[
\Delta k = | \frac{9,81 m}{{s}^2 \cdot 0,1432 m} | \cdot 0,0005 ~ kg ~ + ~ | (-) \frac{0,503 ~ kg \cdot 9,81  m}{{s}^2 \cdot (0,1432 m)^2} | \cdot 0,00247 m
\]</span></p>
<p>Trennen von Werten und Einheiten: <span class="math display">\[
\Delta k = | \frac{9,81 \cdot 0,0005}{ 0,1432 } \frac{m \cdot kg}{{s}^2 \cdot m} | ~ + | (-) \frac{0,503 \cdot 9,81 \cdot 0,00247}{0,020506} \frac{kg \cdot m^2}{{s}^2 \cdot m^2} |
\]</span></p>
<p>Berechnen und Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen: <span class="math display">\[
\Delta k = | 0,0342 \frac{N}{{m}} | ~ + | (-) 0,594 \frac{N \cdot m}{{m^2}} |
\]</span></p>
<p>Meter im zweiten Term kürzen: <span class="math display">\[
\Delta k = |0,0342 \frac{N}{{m}} | ~ + | (-) 0,594 \frac{N}{{m}} |
\]</span></p>
<p>Die Messunsicherheit wird auf zwei Dezimalstellen aufgerundet. <span class="math display">\[
\Delta k = 0,628 \frac{N}{{m}} \approx 0,63 \frac{N}{{m}}
\]</span></p>
<p>Das Messergebnis und der Größtfehler lauten somit: <span class="math display">\[
k = 34,46 \frac{N}{m}; \Delta k = 0,63 \frac{N}{{m}}
\]</span></p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Die Unsicherheit der Federkonstante berechnet sich durch: <span class="math display">\[
u(k(m, s)) = \sqrt{ ( \frac{g}{s} \cdot \Delta m)^2 + (- \frac {m \cdot g}{s^{2}} \cdot \sigma_{s})^2 }
\]</span></p>
<p>Die Messwerte, die Konstante <span class="math inline">\(g\)</span> und der abgeschätzte Fehleranteil (Größtfehler) der Masse werden in den ersten Term eingesetzt. <span class="math display">\[
(\frac{g}{s} \cdot \Delta m)^2 = ( \frac{9,81 m}{{s}^2 \cdot 0,1432 m} \cdot 0,0005 ~ kg)^2
\]</span></p>
<p>Trennen von Werten und Einheiten, Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen: <span class="math display">\[
(\frac{9,81 \cdot 0,0005}{ 0,1432 } \frac{m \cdot kg}{{s}^2 \cdot m})^2 = (0,0342 \frac{N}{m})^2
\]</span></p>
<p>Die Masse des Gewichts, die Konstante <span class="math inline">\(g\)</span> und der Standardfehler des Mittelwerts der Ausdehnung werden in den zweiten Term eingesetzt. <span class="math display">\[
(- \frac {m \cdot g}{s^{2}} \cdot \sigma_{s})^2 =  ((-) \frac{0,503 ~ kg \cdot 9,81  m}{{s}^2 \cdot ( 0,1432 m)^2} \cdot  0,00247 m)^2
\]</span></p>
<p>Trennen von Werten und Einheiten, Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen und <span class="math inline">\(m\)</span> kürzen: <span class="math display">\[
((-) \frac{0,503 \cdot 9,81 \cdot 0,00247}{0,02051} \frac{kg \cdot m^2}{{s}^2 \cdot m^2})^2 = ((-) 0,594 \frac{N}{m})^2
\]</span></p>
<p>Die Formel lautet somit: <span class="math display">\[
u(k(m, s)) = \sqrt{ ( 0,0342  \frac{N}{m})^2 + ((-) 0,594 \frac{N}{m})^2 }
\]</span></p>
<p>Ausrechnen: <span class="math display">\[
u(k(m, s)) = 0,595 \frac{N}{m} \approx 0,60 \frac{N}{m}
\]</span></p>
<p>Das vollständige Messergebnis lautet somit: <span class="math display">\[
k = 34,46 \frac{N}{m}; \Delta k = 0,60 \frac{N}{{m}}
\]</span></p>
<p>Für das 95-%-Konfidenzintervall wird der t-Wert der Ausdehnung <span class="math inline">\(t = 2,2622\)</span> eingesetzt. <span class="math display">\[
u(k(m, s)) = \sqrt{ ( \frac{g}{s} \cdot \Delta m)^2 + (- \frac {m \cdot g}{s^{2}} \cdot t_{\alpha/2} \cdot \sigma_{s})^2 }
\]</span></p>
<p>Der erste Term lautet unverändert:</p>
<p><span class="math display">\[
(\frac{g}{s} \cdot \Delta m)^2 = ( \frac{9,81 m}{{s}^2 \cdot 0,1432 m} \cdot 0,0005 ~ kg)^2 = ( 0,0342  \frac{N}{m})^2
\]</span></p>
<p>Die Masse, die Konstante <span class="math inline">\(g\)</span>, der Standardfehler des Mittelwerts der Ausdehnung und der t-Wert der Ausdehnung <span class="math inline">\(t = 2,2622\)</span> werden in den zweiten Term eingesetzt. <span class="math display">\[
(- \frac {m \cdot g}{s^{2}} \cdot t_{\alpha/2} \cdot \sigma_{s})^2 =  ((-) \frac{0,503 ~ kg \cdot 9,81  m}{{s}^2 \cdot ( 0,1432 m)^2} \cdot  2,2622 \cdot  0,00247 m)^2
\]</span></p>
<p>Trennen von Werten und Einheiten, Newton <span class="math inline">\(\frac{kg \cdot m}{s^2}\)</span> einsetzen und <span class="math inline">\(m\)</span> kürzen: <span class="math display">\[
((-) \frac{0,503 \cdot 9,81 \cdot  2,2622 \cdot 0,00247}{0,02051} \frac{kg \cdot m^2}{{s}^2 \cdot m^2})^2 = ((-) 1,344 \frac{N}{m})^2
\]</span></p>
<p>Die Formel lautet somit: <span class="math display">\[
u(k(m, s)) = \sqrt{ ( 0,0342  \frac{N}{m})^2 + ((-) 1,344 \frac{N}{m})^2 }
\]</span></p>
<p>Ausrechnen: <span class="math display">\[
u(k(m, s)) = 1,344 \frac{N}{m} \approx 1,35 \frac{N}{m}
\]</span></p>
<p>Die Intervallgrenzen lauten somit: <span class="math display">\[
k_{95\%} = 33,11 \frac{N}{m} \le 34,46 \frac{N}{m} \le 35,81 \frac{N}{m}
\]</span></p>
</div>
</div>
</div>
</div>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../books/m-sensordatenanalyse/skript/lineare-parameterschätzung.html" class="pagination-link" aria-label="Lineare Parameterschätzung">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Lineare Parameterschätzung</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../books/m-sensordatenanalyse/skript/übung-hooke.html" class="pagination-link" aria-label="Übung Hooke'sches Gesetz">
        <span class="nav-page-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Übung Hooke’sches Gesetz</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FireDynamics/bcd-bausteine-python/blob/main/books/m-sensordatenanalyse/skript/fehlerrechnung.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div></div></footer></body></html>